apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:7INsu+PRtv+wy9rbuHKFylRWM7jTVH6D/1IMHzYf/jwY3OC/d6j/Iw==,iv:JH6BBbR99Fl811jW42UvLqpO7j/dr6T74/7Qr2TwkGk=,tag:NMcoF7tXa4N27MQp1tkuUg==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlVVgwSnBTeFROZ1hZM1pC
        NitJT0MwUDNkRmtzMnhnNTJrQ0hvVEVtSlZVCmlsSWwvZHhMcDBXUVdPTDJTSklX
        NU5oQ055cmVhVGY0SEFDTXpOZms4b2sKLS0tIHl2K0E1dzVCOEUxZzk4MzUyZ2FN
        aHNZNWNDWW1abjlhRUZVakZkNlZlSHcKkimxs+JIHvSMWp4ea9IubCaQ14t87xWJ
        Aj0c5TlLOk/6QsCAfGqhQ8/c4DtEkQi9/chItiTqrgw1N7A99zI7+g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-08T03:14:42Z"
  mac: ENC[AES256_GCM,data:7hcRpfJerWo420VRBUHhQ4ZwAZHff1js2wq093RhX8eHgmrqSV5TGyn+kiD+0vWnc34FjYaEe6DGneLVRAmrbY1c9IuWr1cLUNkQf1qKTgpNJnFT7DQFOhUmQ/CHcG7yX1QUbNANpILEQgcOmY+/4BuZy5UkfkCLBnRxlgJvljU=,iv:ce5ZB6gWUFePdgh6v//DZELxiuB6n88PyY8tNUzzOIs=,tag:sZQiQ6Ifsqf75g6xKXRlMA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
