apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:yR3Zu7HWT+DKTrntklcBLYXbuu0jYd2mkd8rTxopfLaxKWLTfkXiKw==,iv:EQ1M51t63UIu247RNg+iKcoTNmSCSeBPb1VC7aKdL4U=,tag:nESI4VWNpSO0VpsVZCt2zg==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGVW5nWTVCWnJscndnL2tC
        ck9HNmVPWngwV1RGVmdKSjlDejNNczQwS240CnJVZGhnMVFaVUxzbUxsdGtidHht
        UmZCeTdMYkFoLzVzZTZxajFYWFR5K2cKLS0tIGZIc2lQMTZzajBvaThqMHlBbVU1
        Y3RGcmlIRmY0b1pocWRRelE5K3BTS0UK6P7O+bC6+jO7dpSDQ+Nd4gR91gNIASQU
        XgWMXgBjZktO+/FezkbhE5cqdI8LpJUDxo6IpqiJtpuIN3dE2Noyng==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-09T01:03:41Z"
  mac: ENC[AES256_GCM,data:uVISkfvFH+l3IyDNaDUSVQEBUgXCTH/EvwBqcxJF6BebKbFHt2ehV+7xcAXde7Ifsq9CC8XySw17uUqKzxSo15gc1xUw8zsnYcz/KTW2xUoDhoxdCPWbhfmU9/r7WgWYqtFM/yh3FveXvbeZkj48+CZsWBOSzf3DkGQ3y+dRusI=,iv:B0LJWA8jqhz9jF2DXc296j/PouAybEBALpUQ9K4DipE=,tag:6C+9FGZEILc//H9EE3Qqnw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
