apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:GcCHV2neaVTzGOk29Ybey0JMZEFbQn0KZW3em5QF6v50K2mMETtoZA==,iv:8cQxc49ts+IwMFvm7EVnpJfQMoP1Afw+kweyI9PIjEc=,tag:UZQ8o8q+zBCQ5y43LkCHTQ==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrcmpsbjZxcUppelRIY3hZ
        RGZLZUcxYWFQV1JySHRGZS9zN2tGdXQ3NXpjClpCelg0NnV6Wnd2NFJFWFBVcUhG
        bjRwNUhqQ0xDZjZwSmF1MUxvUU1TS2cKLS0tIGdwS0x3OTBidHFaYmtOMGxrejFT
        K1oydHNUMzRHWGdCZHFpU2xTSkd6a1UKILJe7cULRouQ4v2hFMnA5u5HCf6m2N4J
        WcGZXhljv856rMOgn5qvU8y1rg8TPHqD8KBzsX/RXK8255qAiUbbuQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-08T04:16:52Z"
  mac: ENC[AES256_GCM,data:kAwsIXzUC7h5YuDwPVxOkzzMajbag7gz9xwQjKYy8siAUxafEioygSKffYtmgQMae3Y9O3OaX6K7FYdhDVdNc4QPAoiY7clh+j2QsZ279ITk0tMLmJQ6UI3/7/oTCjY/gIuSPICDa7toge3nNr9YybrNM/5SRwVe0OPfIO3F4zo=,iv:OqbTbuOz4EcOw1KILaiMe/jQUskV5cpQmr8Ynf9i+b8=,tag:EN0xzdXmkQlVYlBHeIuGig==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
