apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:jZiZYHXwzoyIUd67+tNbBl0IHC/T2tDmEl3MNxuR1N9S6CqdRd4y5Q==,iv:ONjT5O9dxqDgTmVoO02D3Xki/jqQ2Ru98hQ+vKo07s8=,tag:3+Ffnrl2WgHTevmowdFakA==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvUDZ0eUYxYXZyWG91R0J0
        TFVHZm54djB5TnJHSTg3ZTFiNDREU09PemcwCnV5NEpIOGRNTlRZNkJBL1hNeFNG
        Q2NNYlpuaFBuMS9CNmVaK0YzOVd4c1UKLS0tIFE2cVFEUXV2cW10TXN3ZEt4VG83
        REVCdG9BQ1IrZXk0alpiVjZsUVE5SU0KiDvMItbgP4lULmkWMr/x3HQ8QPiBY3U6
        CchR/xlhO7Aqgvas1dypB1/zKORJzBWCxhBQrAM0xsFvzIMYewqCAg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-08T18:27:10Z"
  mac: ENC[AES256_GCM,data:FxvaP6vM6r7ul14osOgk695BvtF4hRPokBGktv7PEGTbNP1hgqAmQHwk5NYTOQhDXvayY2SObUIYrkDLjDQwnGUUHIOfQz89XFW9PJgvIvJFthJ4vi0Dm9gsMTu/TWdk/PW+uazYJQLW+Nhc4q/KAS9dzSfkBFDOO5EGL9X509s=,iv:akK0zzD5XF1f6L31RLtExldAoU3JN2qZDOUiitGDQHE=,tag:MKiADs2KXD9G7+XPSXDoUg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
