apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:sg6KSGDtgTgaZXCQOo+dEmDNl5SdoRmwcQU0cT5cRQ9qC9A/cS0fpg==,iv:MrudkvWj+nRDx2iOd0KzbsbXApKKDOtOJctPsGLjLSQ=,tag:N+AghWTmmhy/LxvJGBzm8A==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByWkc2N0NyWEpkd3FaaWcv
        YUw0dWJpNDRUckp4d3Zrb0s0eUV1Z1k4SzNVCk54bFVNWngyVklSL3k5SVB5WHRL
        YVppdC95Z2s5S1VNUENEM1BQbWtZalEKLS0tIElnQThtM3lNc3hKVXRHdEtLOHk1
        Z1RXUWloNWhpREw4OHBGV2hmZzVtU1EKRKk9qdkQViltuBHyH8CjrumR8koinPTY
        KUlHMt6W50p8DWo9l4Qqp0PQnICV9GsbuI+a2zjQhoOzrzT0xDLCxA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-08T03:37:33Z"
  mac: ENC[AES256_GCM,data:qMCGljMJQ2yxsBy/ZfPzIsWOioGfMp9qB04HCl/V6qIX3rrq0ImMN73qSgUBk9E8j9cP9/z9BFknuPrqSOtF1i7Y/6JtGzs4ah6V5w66qdJS7ZbIuIUPpZ+RcIFG9vSjELRGcyWV7f8Uvm4wLljiQSBzgdhUfyYmSj1YLZ8ZrMY=,iv:VcXvP3pOuKcyOugz6E3iuqrguBSIyx3IfN3MywAqAW8=,tag:ozZ8R6/i6u9sqspJZ7lU+Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
