apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:dNIrEOl1f9D3vD42XBtfm8m+shB0/apzATElH3H/J+tNgM2Q/NDN3Q==,iv:s4SziJDYI9/vxbs+dBBX6ybWrsfLjDJPt2rHyMtqYNw=,tag:UJLCw8daM0jVf+kTUjSEOA==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhbUxnZVcrMVNJY2pPSGk1
        TUJlRVdVSUxENXVHZVhjNXJtVFVRdTJTU0VZCloxOTdpaWFWTzdjRS9UbEFzYlNn
        TWJ0ZnBQN1NEc0JlU2J3SmtOb3BTYVkKLS0tIFIzVmY4VFRkbVV4VVJmbFNyZjg2
        cGVtTFRiV3lhT2kzcDVyRG9hOEtkM3MKxjp3m254S85j16EfvT25CxWtH7dTKu17
        UB++DAXZstH7VGm3CPl6wO9MQjCufQtC41B/l/c8Hwy6dOnlZUgzuQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-08T04:08:07Z"
  mac: ENC[AES256_GCM,data:fsiGv042hkTAIPLO+GhTgo6rKNkIZMe0b4E3/UDdR9hbZNTn4UgJEHD4g74R8oKkeKvR/SKWFnmVDq63nAvADyNhLzJB4xqOqj0JwzEjCP1KZWHMO3eD3PZZyqVaO4TC/ubFP1tGCuhbydzFTJsPd5BeLGR+jfuiH9vn5saMyYk=,iv:q/ddlNRPS0xzq8opD9qq5RIV/oskUC702ttjVqje0FQ=,tag:35YyEdugCEknorRcnKWcTA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
