apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:Nb8Ah/uqltcz69TqiVQz/wk6K5PT98S44AGoWqZIYgWdctvhE/jRzg==,iv:IFYqE4E+looEUsV7sX1RvWSNzbVfJRPqFmygac0kvFo=,tag:AYAzT5kAyv8aQ0d35fFesA==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLZGNUVmdoTjhVQjZmVUIr
        TkpDOXhUS2VvOWxXOUlqaDBIMklldnZmRFRJCklEWXZXSVpXWnpvby9RSGUyc3dN
        azRQMlR3Y1VLMm5mWXUzM2ZhZWdUVGsKLS0tIHZqT2ErajZXYk9sV2FuNDhyNWpF
        Umloa244UldQQjBDMzA1K05lMC9NUVkKnalAYRXNVNy+Bvtgd2Rj4dDbtiiH/5eV
        Jhc+musDyjI3a7T4q1Yztw1l7Igvb5Uz7ZC3kWhDsZLZUHQk+OsTgw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-08T21:34:53Z"
  mac: ENC[AES256_GCM,data:PiuLbPnkARzITTGkV7jWE7FTV6JZKLFKdDA5T1Bg94Ag1vONPtgXNZL7oE9AkthKj+5auLFqdb1BSyznTTBiTO3RmKQA6GiNdV9q/y64N1mgRFrymkHKw6rcJoRou/uyHkG3X4eKZ9UF5erS2YukHPdZK8QN43O9keJFNjIvWW4=,iv:mh3GFXDfE7+m4FmNpjsvV4CTOKTEXWBImBcoKXjG8Zw=,tag:sdm9dDp3vR2h1wHm2ZFITw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
