apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:L7UREVNdemwkCmVD80EZ02JtnmTEeajqgWm253gdiW6ihfp8bYj13A==,iv:7fyNeG2TfE8+IwGJsNRhN53cUOlZ89BuHro1GhiH4bA=,tag:ueIN6Tu1+mBnBK7/3iryZw==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBibndmem9oVDdGV08xdkNv
        NW9scWtiVkc0QnordS9oTzRCbWlHb1k3ZUFvCnFHbTQxc3h0VzVESGtkNlJzTUpy
        ZE16aHp5aUM1eGxUcU1yYURHYVRKRU0KLS0tIDRrQ1BzRTlZQzRHODBSRER5bHhl
        b2RhL3ZMQkZ1TDZHM282NmwrejJoUVEKXZMaqE+VPMXoK/QQQH3MRPgbDQ5iOsIL
        szB+BK2VUkEuPS/lXSi10gmfxSXB0yvBS+TydZ8VpbYrJatteUeAzw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-08T01:47:42Z"
  mac: ENC[AES256_GCM,data:weD54tbjZyQzqXW3oZEOAtyx459v6a/PIsQ/wUIB94fEAurzcD6EcRSZGC2KNcnLrH99lZ4ATwy2Sx9NfqfTjZettNNNcgMBWMp+9GQputf9cXJejpUTsSALtVyCs2TG6r7VDtrpIgRlR0qqMkhZ8QxU5PG2IEd0w+xxWr6ejp8=,iv:hx3kq9CmhcA7+/U7e5MZt30BdpjO5d00lZpZUkp7I7M=,tag:W8aT/A9nDFhB331qTbcPEg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
