apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:S3a5qHkKL2szZWLyOSSG5I5XsKjmW2kjWTeEdfciuEcNjaMtVCPWoA==,iv:t0WBgL1dXA0mmADpD2Y2oWTYQB1D2HAxuA0XL7Qz+fI=,tag:x2nDVjb0GCyP+lARIcZYKQ==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTa3d5blVJOUNkdFVuWGxt
        eW5oQmdFcE1OUHNIUzFBdGNUaTF0dk1VSTM0CmpmT0p0b2w3SzA5ZnNuYlFvMUxN
        SmpPeVNoNEwzdXNOVENDU3JKanhCeEUKLS0tIG4wWk9DYUp0bUFCMGhWRkxLV1Zy
        U0xYSjZGQTBiQkE3VDN4YVJaZXRFckkKsqaGBHNEZ4qubHt8HffH/Fee3B91oZu5
        /CCsL7/Stl7bS9iFDfbc5/KWIIqsVyizrSV5hg0FSF/NciPWEvtq+w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-09T01:29:57Z"
  mac: ENC[AES256_GCM,data:1aWn6O/e2q3PFs/xNzG/Wd4giK/RgMiCX8VffgIj4xVJGhV86FVYUSTZE9wxTyupo84AH718p0tuqFvUqSqa3dzEAVwlAvXrdR/usR/ECl67XrGb2KlHjD0g4AmvOQi5saVlC4+gCMD9bs8Skt5zkhPKQcqzTyNOamxdVLNvMu0=,iv:oUgfQJ77Xc2Hgbvbb5jH4i1CriAdCfZD4NJdeja2LEQ=,tag:OFLSlduab0NBgJ/Axez4aw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
