apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:sU/JwItuXfeBls3SG8LROXMb/JrPw2GpERARhffOAdKm9Y6qyoRFzQ==,iv:xlbHCu8lTulRhYUAr4irW41lpmixfQzAsFSiAhFOpmc=,tag:3xeRcg6ATtc5r1edNMYPsw==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlazJqZ2RLdmlyLzdIekFu
        UjYzNFJXS1Axc0R4eVlOL09rU09hYVd0TkZzCmVsbkNYazJHMjdjTU5uNjhibGlR
        c25NQWRseUZSSFdUMUdKOGJjT3Bnb0kKLS0tIGtXYnlFSnVod2tEQ2x0UkhaUjkw
        VFdFby8zc0JnSklhUWhUWklXTS94RmcKK+YqYhDhghJ7VBXDZrKenNawSvwmLItA
        lgjmJI4Sg7MjgsUGxJJV4z347ugso77GqG+o2joWR7dSsdEWBoUAgA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-08T03:39:47Z"
  mac: ENC[AES256_GCM,data:YT1jKaoGTc29rJRYBgCdHsdL5AhlJPPiax/oZsBLkr9AKPsHRAC4eTspXPCSCYPsQhBYGuwHYOfyO/a+zWJogx6xnCPBpeZQ5FniAMHPgAbObpgQnLG3DUtZ6fpfx2Jp8ee/h9fchmWgjCBPRKY3MeEvoJfTpBDqEcTOSbp4JnA=,iv:67RMaNdAj7wjXcOM0Vrr3y+HsIbO4JMt9X0Mt82e5ew=,tag:yD9PTsxv8GcGvSg3R79jMg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
