apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:pdnMB+GpX0Mo1UFUlLWQ1F8Ob5n5gVbwEYhuFyZV1t+bREPSbT0LuQ==,iv:EEpGB9yyAvyTm3MFZicDQWzyDvi/zaEFbVA+au8znGo=,tag:tATqJD0NpYRfdP3XZdWEEg==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHVmxMSHczSDBzQndtWEd0
        dWRRZ2JLNUJFTDNFdjd5SHNjSHE3SEl6OVE0CmJMazY5MGdYRG5QV0xUSitYanBl
        TU05ZjdpSlpZeFBrbzNaSzRGY1h0U28KLS0tIGlyQmViUWpQK1dCdzdDQVFENTNw
        YWtBa0ZxSTJZTDZuc0dDSWNWOThXYmMKcG/02NrfrbD8WrqOI6x+lwAfSQDg6r73
        GRHhdglKjziFbtfhVpixJPS2m1Ldb9fbmIlVOQ4w+QyU9E9EASxOSA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-09T00:13:26Z"
  mac: ENC[AES256_GCM,data:7iF7Fqu76feJlBJ0rGIV/WmAiGknRDa7GmNwV2ZSOFoNXcOgM6Bi94DhedY+zTbI0ua7Ew5iy2rpeEaqjnWybCVSfgMYSB0sMs90XGQPYRX0wWSt7JniHwnpX/QsLLOUwKz3oPgQ839WOHv3ZypXa6TT438w4RNBP/yNmw471j4=,iv:P3LDJ/FwTWCEGt+n2gwoODQqfp1l5x041y+DMpSobR4=,tag:5+v3tKWhLc/hsjb9L+nMUg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
