apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:7G+V5dptdEtrybr80hgNxSsKNAiatEZbaqJ4dwnO8zg/zSHGyXy6Nw==,iv:C5xMj51FVX8TvJVHCXuV4yGQqxnmphiYqxw1ecfk7Xs=,tag:uDehq//gzXahtudLcYSC3g==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUS21hY1NtNExvVXVhK24x
        VFFaK2R1M3lnejdzZUZwQ2R2UkRsVmxscDBjCmQxVStiaVZsVkQzT2RvQitrK0Vy
        aGk0MGlzYWkrejd3RUwwMTVHZDVFNzAKLS0tIFpsUGw0aktidEgraVJMenhEOUVB
        MjZhRW9BSy9VYlRJWDd0MURNV0lSWjQKOylg4rXqYFgTLTgPGQlBVfojQ+8Aut1y
        HNyfJlyI6wfNe4lsxBTb0A5kC+aFduSNOMdx6UO1sJJiYzPDQHK17A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-09T01:52:52Z"
  mac: ENC[AES256_GCM,data:nMzCKzVL0wMgRU5qCfIEOc9kKMxB3sjO7NSqsnhY7pTM3+xOvsNL23C+cZDGo0SyosBXQF+dNS2HOtA45OwB+hpCAQf0tNfkmnR5U6fl3KxTPxrzZ7tiG7WgFrjX8v6wdSrUMRF54eKTMOfBx5QfnkWxkur7xhLOLOhHfc8TUgY=,iv:tgpCTb6RrjQCLhyWmK/DzzN+SO0SStgpP7JsutMN8pE=,tag:IUBuHrXXBckh3L0g+/YY9g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
