apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:rja5/wRV/zf7bCapusTYgOyM7WMM8FClFAOekqyOX/HF0DmfD7J5aw==,iv:P9udMiGSMxkNY3KctkuIliB2kmRzCwbUp5RCHPeQgg8=,tag:18rFzB4BHjJ1BaQAuMRkhA==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4WHFJM3FyemZ2SGh6QkNl
        WXZDNlZSdUNDQjN3cVFhMmNYeGJscVRIelVNCitpS0F0cGhkK0I0cFpjcUpoMjNZ
        bkFDb1JxOGZnRUZ3ZWZWSk5lV0p1V0EKLS0tIDdyeTN3TUtpZEZxalViZFBOWSs0
        SWNCVFNaWEtQQkozUlNVcnhEQ0tuc3MKll8cd46Bbp9ijfdw6t7OuWe85zYrmNhi
        LLRSO+DNeuoxJc56vAm8FIY+A6NLWzj62MffdzKWpAPDy/hKZ+jAdQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-08T04:11:15Z"
  mac: ENC[AES256_GCM,data:KYo3UztEAvNDW1wywDMrEW0XgzdLkKRDRay9ozgBNcgGaPvlQDC7yROw6k+hNu7vRWcv2uQOZpTyjnY3dGIAsMKZhuATvObQX7KZGBBU/TMIuSMhDtf1VWYMYWunINnT4Xvhi7nb4NlVsRe+vaUFbKIJZDr13ClNAXe8tI6tAIc=,iv:FnU8ouTpqk2JzCYgo7o93ri50Jm5CCXTokh8tjK6c68=,tag:BU58GcwJuvRjR8dBUSVihQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
