apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:Dt+od5n3ghR8k+z92Yq6Bm6NrTKOh7EWXTxXLn8+HatsIhb5CDQlTw==,iv:G5JVP+sPLhTQhm+qNocuN3m3aovoZsEMZK3Fa7r+Vec=,tag:WgFE9lhhUUruP45Buk3UgQ==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCZUNCS1RzNWhYLzM2OVZ1
        bjJId1g3c29BV2R1NzZFV3NmNDZRbnJ5L2xJCjFiRWlrTU5JUVcyNWhNK2ZPblkw
        Vzh6dGs5Qi9rV0o5ZmNWN3Zpd0tOS1kKLS0tIHhUNEJKczBNZURJckRYczV1d0Rt
        R2loRGUza001ZXZ4b1ZjNFJSVCtVeVUKl7juW2Gy8i2JEJzIV4T2ec1WcST0zi6V
        /WyZifp3e7FTn38FsQIvGZav/v1W5XzMvh2gTm/97eXnsbi0OBNopA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-09T01:07:39Z"
  mac: ENC[AES256_GCM,data:HtBI7Wx4wppHXbDP46lSx4/0Hdb2doLGV3n5nfZ8oSOG/akXgYI7BkGD+TJv1nNCBdUcciELQZHyf89tfxkKjicJxIsQwCqLeJg/ZkNkql29QrqftQdDhDU5OCpgeXkXuSoBqcnbvuUZFszafes38HYZJIgOvf7rsUmefSDOD14=,iv:kZhzl8KESGke0AC7V5PWXuP9ZzTP6n+hkAbkq4IerGo=,tag:b99QlkvH3oYQyXu9ixeWkQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
