apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:H9jFNQEvNWFP+ysuQPWq+mZH6n7A2pRDtyPEP5oWkLIjD19DrhnrzA==,iv:rN7DF9J5ejalnHU6Q1kN3KOplR3ZyOBwUy4H7ph/N4U=,tag:s28lbcgnzz27jNIkFqrhuw==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAySkMwZkJsbUo1Q0svUDRm
        VlAreUNhbXk4eVJVRExXcDNVU1dzRU4wQUE0CnE5dXVDM24wTWg0NjBhTk04UHl5
        R3BsOGRnMHFVYWZvbGRqL0duSUlJVjQKLS0tIE91NW0yV05PWFNHVmRMSTlGZVBU
        NWFwM2xUeUcvZzdETXNZVzAvZDZGbjQKdO0iGeX+iwhbMhxAZYaoQuKi2Zx7Tyfm
        RhT0HkWmTJ/Pyjn5N+z13GNDGKtKRJ0Crhr3iBA/RMXwr0+MWIBS+w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-08T02:29:05Z"
  mac: ENC[AES256_GCM,data:MWX20wPqZnfBxAKs6wCQxDBGOwC0shJKGLsHIYB/asiqmlt848chy0+c/WT6K3d/elwMom3nCOHBkgO0eBDM2/DTgbNr22lt5UfJ/Wqd+HuRcyj8BBM3eccY7NTjGi7XdFY2XSLeU3LI53VKiSbgZVPIwxHmI4RIx2jw1wTWxcw=,iv:N0T9nMfCubJpW5/0JIUEyuSuPCicqpbKZyhKHEaiZ4k=,tag:a/arhlkiAY9ffUAvjTS0FQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
