apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:D019iarO3CDzEfc9kQ==,iv:3YlVEZLrn8uLh8sClqVmsEFCkdSQxsXg7n+JAuFQpKg=,tag:adr6zfpYhKAuQMg+ejzBDQ==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaTWMzSlZoNitNcUwvWlZn
        N3NQZEtNQXZteUcxZnN5R0RvNzRTRm1pVUZJCitnTk5BUDRNZnpmQVpTRHhDSXox
        WStPSm11UVZrekszd1RwUkZUUHVpN1EKLS0tIHF0TnJ0YmplZFlsRGRDUnp6ZVJs
        dGhnNmtKZVl5S2o0TjJ4NThaRVE4dHMKd2A8vY1kywAshvXHKnHKxFFz7aaF8dTf
        wIr2GfzSTYFgYnRDvONEUI5ZyTiYkgt+4UodniD+WcIGIacGopVSKQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-08T03:14:42Z"
  mac: ENC[AES256_GCM,data:cwoCsMUsuczAoqgLXjavL8SsksKW9gED8nOV2655lnoL979NaIi8ZFpwSPVKFNiBBEoZzbnDfuTK+BfgMkXNPpNAk+MJSrhc5C/g5CYXfK31CMDRisLUTRqVikipNJGPC0/GA1i89+Nf6cs85gvQN1t6VKD8u3aCMcgfo+851TQ=,iv:rJB02KZRBcJuuMRUVkGA8hAzFlyEAAbR2jPwWXkiok4=,tag:3dH9WgDm2Y9IGLwHsqHmDQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
