apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:3SeeIwyrfI+J0VHQaA==,iv:CbtGj1AcMJKUvuQPpTzsKVlDPEcqbPekl9AJIIFM3wQ=,tag:WdzkcIYGAqNecJHuiu0cCw==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwbHU3Z3I1MHhLdVdMNnMv
        QU5tUnVUaHNzMUZTbkhRSytkQ3RoUXZhMlg4Cm5kbWI3c3phY2QyckpzRVI5bXZ2
        RTA5SnE3UnBCcGowVXk5eGJHVjNkNEkKLS0tIEl2Qmw1VkpjanRGdVJDVFNaajVL
        ampHcHVpRUV2bUpPNUlSY1hkNkUrK3cKRQxPFaUMjVa/3M61OjVjhVKvE6Rl6vLA
        m7k3eoh6eDrS/n8ITczbkciuZb/UWsCU2Kf6nXi6RBhWV8hCw5Ph3A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-08T21:34:52Z"
  mac: ENC[AES256_GCM,data:UGLYCDa1ibBqI3zW4sisO4DaIDQFvZwWnISgI5G9D5AI+aVEpNJqVpIRfxvuxEl1KziXJeimYjSJ+hpxENgX9uQpE2/iFFL5Iy3wG10Y8wXO25mQm8L7eRTANKNZ8amC1dwmN4sVREepyMAYAmqjUk6IJajjiAqThL8hzLhtGM8=,iv:xnVprInRbvmTRZw8n9t9Gnyoli9AEx+ybHP2eIjJ+vE=,tag:fetOyTSiwrWvj11M0h6sjw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
