apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:x8wCoIxIbEp6Zx+GDQ==,iv:mtyUWJu2nQbyHeuXz75Ij+naj/IHO1zYgayntUwIpGo=,tag:PGcKcs+IXXnqVJkGaECr7Q==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaeSt2QjdQeUt2a1RyaVIy
        ZEhIdDVKQ0NOT3k0Skg5WG12d1Z5ZDRZLzEwClllQ0VWWWsxNS8rRy9kTGZJZ3ZO
        bDF6MnFBMTQ3Q0t2Q1JDak82STArb1kKLS0tIDdLZmc5a05rRWw3WXhuNXZ2ZTh2
        b21KNnNKRXNmTHBWTGd1OG9KazhiMVkK5MmSA8e0Ho7D9LC374edjmF5ky6zm84K
        udE4fOvEaabDJyIInNh6oB808IbQnXn1OlwOgiq9hrm4Dp8pCTvJqQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-09T01:03:41Z"
  mac: ENC[AES256_GCM,data:ducIy1ygtPZCT8ctU7ljQBZE4O4U3KdC2aXZd1Q8SAWtIISk1omeDXe2/SXYtEdY+wnbFnjsENvW6KQ28u1jMTKwVlSbPHWpzm5KrkVCTJhNkUpZh5eedYzX+T+B4aqu7zfUiIyn/go2EbazZ6XFCZvmhH9ZdoKgONbbh8q2ay8=,iv:kfbIsh3SLLdQzICNk/uj0PnLpvTVnxmeqa3h0hePrh4=,tag:P9LZHAHTdzFIpdsN050XAw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
