apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:zSIUsgMgBK7kifGKxQ==,iv:jtEqUqc703pOmC3GfuSeuP+3uejG1inQe8tYSeRxuUU=,tag:ca+ywwZZMdmp40nbdZPFGw==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzKzFGNVBDYnM3R2tkc0JZ
        eU91UXg4eHlML3B2TCt2RGpIWDJTQkVsQXhzCmVvYU5iUGx1WUlOM1o1NURiQ21X
        MFRYcENsNnRDaVFEQUYxRyt1bFUyZmcKLS0tIHU4TzR2aVZEUDdUalVJcU9WUE5I
        ay93Q2NwOWlrRCtFdUFmcVBONkFlUmsK+Iw3fU97gY1QiSV9fjgc1kd4941GKr2S
        KsAgyh5uzbLDzvaiov5WNRHBvBPrgeUrocI/JL7vBqJzZMEj7i2yOg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-08T01:47:42Z"
  mac: ENC[AES256_GCM,data:bK59nTs/ksiZY3pyLNXCJ8uXhJA4qrmwNtbs+TZGz5mjDlmVkCwwE1IhV17tpE1OS9ZmgTP5R4I1hgW0hHZxdrtPT6fAyVbEzJJAVnWAoJgIA7BVoWnkvzlBbYmYLeo6BPmLs0nSQBciVSsahE6s15e9ZnJP2J+MsmAN5805tPU=,iv:FNm1Vo3ILe4XJgLeQx5KVeesY7Yx70CIqm1yhzMChBo=,tag:T3QfCqM6/U5rFL/l3op77Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
