apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:waLHLGAcqSkURBPk/A==,iv:PQ55aCLBqkLyOyibrTvUg7wsMooawY71jtCrja/JdMw=,tag:lUqAkEoL1h7tLCFIG9KMJg==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEeTI1ZXduWHpGMy8wSEZn
        NnB3ZTNqeUl0bzBTKzA0ak4zcFY0d2NKYUdvCktxTlBzRW5raTVoajlSSUszU0J5
        NFlPaC9Kd3RYQmFQendEYy9QVyt3NUkKLS0tIEhGWHh2WnpOa292L21uOHdmZWNI
        SzlBcVFuREJEckU2L2N5QThRZjNyVVEKZnS70JXZA6DHEpXYMlkTADWdmtrNg1zZ
        uYi89ChKcASOIu3mwfsDThLdIhgSdUhhWFeTtGjjF837gsSopSMDdQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-09T01:52:52Z"
  mac: ENC[AES256_GCM,data:oEijb4yFOTgddA9hMu7MAuGGcPoa51g9/6/lNJHBAf++f5WPHrVzdEip104o/OiYE9aeb9vLyenzYUuJw4SaJ08CyAkt0FoewkiuSSChCpWidPnZEvD5jJMQ9jIfPJ0uQUUku/lPXok3GfTiK4KxJoIqRC7j0SBWn2H3wbWckFU=,iv:dJTQzXfg3V4Vvl+mhEmLPyGCddmkrWkWSgCKI5LspEo=,tag:j5Ftfi1oqA7LX8uTN4+m7g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
