apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:wCFQ+cCtQopCG9HHLQ==,iv:t2c0D7hVy89gx1DySvxAcXXnt9DkAWKkEj8EQVKqXrQ=,tag:EKDqsVSUdsqzAnW5DWo3eQ==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtYlpnc09mWDJUZ3hselEv
        RHlnSDRUUW14Y1hnY0N4ZE1iSG5nMDZSMmhBCm1CbmR0Y0xJQ1Erdm5haE5DYWx6
        UWVHYXJCQmVMeFNlTlFrdjAvbTZEaGsKLS0tIHJ3aXNHMDhaQkl5OXphVHc2Wlhn
        K3YvalZ1ZW9XUUdocTdxb0hFWUV3VUUKOA1tbYAbcWXET79HFwOZd8prtxlWQTO8
        gC4FZol3KcwUHVesIZ+jWStxXxdcj6fzdC/g33AtmOLUVZSNwpLw/w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-09T00:13:26Z"
  mac: ENC[AES256_GCM,data:D7794GYuZyOFXExzPU8EPsohuvnUAevI49Gp2Y2jocN2AE3j1n32k2NNAS5pgH4MZv0/CaJIUTbmxg8lR+TbaU6WOFTxEgOu0rnwbxLAfTFB4qXtCD2zVy5vgKnMuYDaoQ2JhqSZtwuZCoE8mQbtM/FMAAgZl/mIF8iEn6h+V0Q=,iv:CeWLwZwAKOJF3Dwktzq0YmGLYXKhavcvBIhRCYW3XBI=,tag:Alw7H+11+xgL0MkMMKkk/g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
