apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:00le7Id2G9h/X00l6g==,iv:KefYypESye+24m+3tqwcB8GX20QhLQ54tiePumTb6DM=,tag:1ll/L8ACtEmcAM9XYRkQSQ==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFV05YeVB3UG94K2MxN0VV
        S2xkWm9xL3FwRzRTRnFNQUFrS094VDV2NkRjCjA1djhjUlQ1ZHNGLzRHVSt0UUdN
        Y1plZ3o1VkI0WGhnd0toUDlTM3FEWGMKLS0tIHlrbHBqdXdqaUN2VkEzbm5HdVA1
        MTZKNnJRNk1LRm5UOEpMalJrZEJTdFkKNcZdfhIWBufY724cCzSrGQiZ2AR2RcKl
        WfiIU+djBhSWsgU9Mqp8ca9r17EFSSb+g+KdrwXG9REOduA2z7CGMQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-09T01:29:57Z"
  mac: ENC[AES256_GCM,data:hDE36Gg8aiXdwyWlgVXRvIOAthMZKG6FyU8O0THeKV39UvucHYX9qXB0xom6Xi294ASLv37dOx5CsYDXPOc6zSh77Bi1iB06PlOP7+m0YjICfMMsYZXolZcAXKgtePhygVv9BqWWctQpmt24oFohiUTrrw54gImITjU5551o1Lw=,iv:/IClrdXrWPjcysmWQzMzPAXfktYl8teikIr4izAHJ5I=,tag:pYaXN1tq/xxnugUh+VZ0WQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
