apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:WFQfQlXvqfX+rZ3bHQ==,iv:Ca8ffUTYD/UciE8xk9QF8rYVOYQMthaL5sHF9ie/kfQ=,tag:vXMsutxtjCQipYcl8lngdQ==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmVWl6T0ZITXAvUkVCUm45
        UG50Z0pkc3ZOdzVKQmJ5ci9ycG1jY2d4eG00CnFuZHpKRkNuVG9mdUJROWdESERW
        S0k5OE1mekx0bXdUanZMZ0UwN2hvd3cKLS0tIGlDcnhseUp3N0pWa1VyZXlwSGNV
        T0NKN0k1eEFYNU51NHZxc1NZWDl6OE0KFI4bRccl1j4Jwf40TWDIwSKMEoL4qN0q
        v2glGPDwvYGwHCDfyUnhHvOwm8zWxXX9am86t+qxBW95WBIqdzTQjg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-08T02:29:05Z"
  mac: ENC[AES256_GCM,data:XHmWGnqgZ2QGvuk6GxGO6Mr8RMj1ewg5me6LZlK/4S7yi9H3Ma2KHXiMczDCRARjakFACgKdnTII0XGU8zyDCRFWF9Y4EDes6BDuQsS8p3+Y9h5QB8DJQSWNaggPQhCa5aNdi19bOTHP9m/MiVaBoGBoXoSXHhVQ8BUest+ymlo=,iv:gd0bmD+hww99XJfAA8hwmYoR+wj7GM5ogKiGzS45m4s=,tag:9js65EyUp2a4itQJtbQI2w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
