apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:+1mIAzndAnsZQahk5w==,iv:jam9PLbwGRdIIeyJEMC2qQWh1NHEKqBwJ4h0Zkm9wVo=,tag:SyxUBw0EqEWO1wT5j9M2mQ==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnSVd1dXBGbUlXTDFyOG1G
        S08zL3licUloSlF5dGE0NkNTa0NTK2xzMUF3Cm5DYitNZ2JrbmViWXdHWUZVN3V2
        cUdLd0tJTzBCN05GR2tRUkZuTzFsMkkKLS0tIHYvNyt5UmNYVWFwNUtCSnNUc1JY
        TU0zdEhVMUYxT1BmcDBFMnhLdXpxMVUKICpwyb41yyjuThjv5ikGn6KG/PjhQ/PU
        YN/wQRdSkHlORAs/wOiCLhujKTCeLD6JnUdwCAUKOhmdeyLK5BIBBQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-08T04:16:52Z"
  mac: ENC[AES256_GCM,data:EKsb29xkkIRciThwMzOrIK7bQKyANX7FHd4LJcR9FULVQuzGi++pSYjCT6zxw8t4go9CrDgFBky5X4WZ870X3DP4dxpjthmlO0/m5KgNQHsGTOJKFuMeCO9i/hJ2ZWmVx+zOqhfsDJAxvUx8Jh0+SvnVOZgqLb+uj6U4JYkkX9w=,iv:fz6H9RmaP9YRMI4gh8+8MBRY6ZGSvLFV3NNDQ9ob79A=,tag:gOgAQ3YuYcs4VFFyYQXFng==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
