apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:1p3zUpOWtNr3InbVKQ==,iv:y9lk7/OdxDuhDcoIkLrkRP8Nprlol6GmgO66y7qtzhk=,tag:wlk7cu0xDua/NaX+aS92Ag==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyLytYOXE3NWdjUVlXWmFP
        K0U2cGtFYVJuYk5pOUJSaXBHd0cvMUZ3NUJZCitSOG5EMXhzUCtXQnFiNWxFeFU3
        TGl1ZTNVektaeU5KZ1FQbjZ0bG9pN00KLS0tIFRyVnJPTGxiaU9uZGNGTWdyT0lP
        OFlkam8wcmozaXRqbEMvNnpYa1ZkV1UKvVNyUBspSLE3SwEnrn4tKm68Ke1dBDhi
        CD1W25+FsEcCsOnSWp1MlNsxd84s5V+VkuceoVN3Gm1o+EyXt2Wnkg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-08T04:08:07Z"
  mac: ENC[AES256_GCM,data:cL8PI21liitlhPj7UHHKYAwi47LZKwzBg/nPy6GRniK3p1KacShKOhqQpK12dYj1HxHWOGya5HCD5y/3npgI+v4XZYnrHxr1ql/Vocj8HURPpq4SMSulNJBpDIq31uOEFNDnr65CD14IiGFUtCaMpb83xCYPtn9a40jDRX2a60A=,iv:DhwUyz7+eJkFyvnzF580qQ7EC/6KWIYgzOpMIR61Uu0=,tag:+juwjYkZh0U5Iu9OFDzAZg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
