apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:K2gy7X3BW6zYt/n3jg==,iv:NqVP2m9ThesuX8IEB/pYA0RStYIGIsDr3ItvKt4/Xr4=,tag:Pkd6OmEO4TgN82ipqiAX8g==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqTFhHbDBMOGZNYitSMW4x
        Y2hzN3dTN1VaeUlWRDFBR3g4WmpHMGJCS3pBCmRaZENNRE8vcTdZdTdoMUpMSW5F
        alRSZnpObzdhVmZIcFA5U2xMcitjUEkKLS0tIEg3c2xnVXJMOVMySnZlcloveE5n
        RElmcitLTitDKzZVb3lEaXJETXliUWcKHSI1NaITpp1z37jxNX6s60MDrwmweOtC
        pvaZ+ef1wWQ7eT/e94qajT0EUHVkWkBF+ROvRx4yhE8ISzDLkFPI8Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-08T04:11:15Z"
  mac: ENC[AES256_GCM,data:ZwX9zEZrrvSDauOzkWz2JhnMEW5HgC85EMPEA31unBpy6FOLWwhKephAxwjXnd+xOecT/uG82cWC0/Xfw4wr671YwxAAV/D/IxGLU2s40MSGAM3DG1bkwmPOtPjkFRMEvl9YBUuIQpl8q0MgKQvBg0b4/gqMnGXWWQLgXRcottc=,iv:dD9Gv5cCGN5X2lCMgYy4T1bYKyi2H1lcL1d0QjtjWqY=,tag:UpVTIOGkQZtzqqbODEjL7w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
