apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:Xllp6CZZ3w5TX70f/A==,iv:IRuDqzyYY+9OKg5cjVCXkibmX8Wb5ME2Wt/sDCfpoZM=,tag:lzxQ8QFr7RRXSHhz3Nmq8Q==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2NUhBTytZSno5VmVMTUVX
        aDNLUkdidHUydnY5UStWVFRTd0NTeFNDTzJrCnpjcjBZbmtKUEJNODk5dmVFbTNi
        ZnovWm1pSG9XVGRHL1dFcWgvRStOZ28KLS0tIDdlUW9DNXRDUUFYSHd3MjJCVWlY
        MEJYMkllZnZDMEN4Y0xRL2J4emc3eUUKxYMKFu+i71CY97elAdyjaExY/n1pnvdQ
        PNW178cBbf0m+PI2FvW1Pca1476wc5l0msXAUaoSLO7cb9PFJYHPWA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-09T01:07:39Z"
  mac: ENC[AES256_GCM,data:0E3Terr25DYnV2NeN1JBsNMstFSCO0DPGSNxjLICoUD46eCB9mcGDbbJtLXfJ6NZDvN9uLKB4zAhNF0UYJo+fWpO+Ox/23CMNn3nIe/4q5KNhEol7sJld8JFVj6x4eAKNX1ft3gMSEfBLM63SNyPt+W7slUXiT5ttYACL7Mpc4c=,iv:JEudfFM2Ag1Q/Q0bqsabxxkmfe2EYuxbMNLsKsrHbo8=,tag:yrGowyq/tIfoHxOfb0e4Dg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
