apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:O7IsM75gpjqzA/m0uQ==,iv:XrdBPG4BD+gMMQb+Lk+7iDTdCX2Tr6YEyA7p5v8l1+M=,tag:/+xwKlxLHbAyfinUr1JKTA==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuc0tDbC9CRjkvUUh0WHNw
        NmppTTNDSDM5K0J1TjlqK01qMC9yM3hXMVVZCkg5NmV6ajB0MjJPS0xWb1JQS2Zj
        dy83MDkxVFplQkoza3ZVUjE1dHh3alUKLS0tIEJxZ2NWaENub3NWQVJPbWxRdGRW
        Rm5IaDEwaDRERmFlMTlQWGlmYThhTkUKXG7LxR+TITASeYqVtvUz0pAqFVXaceZu
        HR/6ze5I7g4qflCoBRTX1ioAEAA4m7653SjDEWs8yj8Qx7KC+p6qog==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-08T18:27:10Z"
  mac: ENC[AES256_GCM,data:/z7NBjDqAlIAAzYfnVmyYXDQUc9MGxCAxrYRvFRWepqDN+riO67IxbgqycvdBlbJEF/i3wFJtu0W4eVwjwfKjls9Og/m6PuUZl9jKW9CCJEgxI25jeC8ynmWayuAWwABgcVdFVe3xIUo947DiEAvcp9O1sV2Q55hdoWukvZn22Q=,iv:QniKudTsc9n7SZ6dXN3iknH2EIkR32h/JFcasoGr3jU=,tag:CwKmUT5Jw7kraJ2TQRU8WA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
