apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:d8Pf3L+6JDgkEimS8w==,iv:vv1v3sNK5+KsFsvE8rGiI2zY+dIUuwupgxepPdKOWfQ=,tag:Q2pDRJZqNYh1g+MIlTmuyQ==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwOGVPUWxrVVArWUVmajhS
        L0FHZkhDRGhGVGJncUQ4dG9Mcjk3cXV6YUhrCi9uaVBwbjdJd2FrdDB3R2F0Nzc3
        cExjVnBCMTZTS2cvbEVPcG13eXVJUncKLS0tIEUyZlkwdVQ2L0FYK2hlQWdvRE9L
        bnNnU2FJU0VPbkZ5Z1VKYkkxK081WFUKkKWxuUReAOJopp5mJoj3wuqiZUdQBQDw
        5iYPNHiOyaN1wGahCT6UFNAO0ptbpqcAhoo6pti3wDPeIel8mgMJAw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-08T03:37:33Z"
  mac: ENC[AES256_GCM,data:Iy4cNvip3fgUfotk2pjRfc/F+qr8DDOjMhCuVO1GlXdeZ5fCuf1cvp8rxoY8kDEJkfIbXs/nnCTEVx3IoTV6zmNSzTscUyayy/hFcud5jP6ZieLMJlZzOCv9iU5UgK/0zjtbqYVoRnxuQ3H55FMjiNkn79TVPbiww+DKfPvavl0=,iv:unZgIckYb6xJwwFenSbxQWo1KLKMER6ZhMI9agiDSwg=,tag:nVWkya43Bchf+bS3iHrQhw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
