apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:ZjuKY+O2zLx26S5N2g==,iv:XYtp1c9hkX1bOzmzBqSczYfbmyihDQ6V9y/BDEKPLoQ=,tag:ZEoaZ4b95J0AToU5rHbhVw==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLRmJsWnExWjRaVlNDekd1
        RkNzbWtySkxVQ25RL0g0OW9nMDVKTUM1SWdJCnY0NG5VOXVuVFJ4OXNrNzg2cUZQ
        SkdGUG56Yjk4L0wxUVROQTQ2VDlkTWsKLS0tIE94bm1zWHN1QXFveU5UMklZQUp6
        OERnbGpUNUFYaGwweDNPVFNOekk0UFkKEurrqDY7WRFAGc8AAT8zQj+n/ZPrSS/V
        3XPzkLor4NRCCAi8rI5Njc8W8xfV5djN/AvcLtgvCfNWdbHLpo+4Tw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-08T03:39:47Z"
  mac: ENC[AES256_GCM,data:woEO4n5oFqyvHgLQIf+c93yRiIhv8eZV77sptFKFYNnP/WzAjfPIi5Id3Y6akgZh1botyv6cLxJkC31Vh7FF6ojdKdNDFAGqS3rzxtRM/2fE8FJ3Cb6UyRlel4IiHxwkw26oynPIEaUWkhLVtIjUN0AiyLvIBK/gPPVCHLcXxEQ=,iv:Bsk4N5RkZ8mJIBuwHgOZhWX1MHR9vsGTeTDRK/959vg=,tag:07D6weUaqN3mTCrZWZI0mw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
