apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:/4dow1PlffNw6AwUgFNatU4dGP4AGYQlIZxI/ILXNIQ=,iv:tXbH9DzpF5z0+SBqNisZEkecSyhQzN8mMPjxl/xPG+0=,tag:eByyjMRXLF6YP03ttDwmfg==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArcFcvd0V6SmFwdlZYQ3Yx
        VmdQcXh2RWpUdzdzQkFNdnRJNi81RjlxWGlvCjZ3d3M1THZpZ0pxdEJlTFp0K3Nn
        cDg2ak5VY3Zud1BKSWZ1dFJvWHAvQmcKLS0tIERNWFNnTlN4L2dadGxXSmxtMnMx
        bW50SkRBSGV1eE9adlV2WDBralI0cVkKsjRpiSsXxMCQe6wN2fhwf5IAjLr7FuG5
        tN1NJTPTnSR2TyvhLb+VyD/freB6/dosQXQnILWsPkXklkViCYpznw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-08T01:47:42Z"
  mac: ENC[AES256_GCM,data:SyHDgO02UBf+Dy12/3pUtQJK0452GXO+wIz7SY2VU7kwgAgHOl+clW5Upi1zi+/hXKGcn+SwKpe7fPKA7FHGINgkcHUAow/dyPvvIQI9SV/dJFHTmOqdEGJaGL+GRLrjVGQyzCNRbemoR2f26qTCSuaGL/7SRl5oO4d6OLIXqRc=,iv:6eKQzncHXVhfkCpgUtk3l9HBInHc0mS3emKvHwx/y0o=,tag:jce1U6YA1VbGZHveeSYOkA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
