apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:PdBn5asueaC6iumBJIhr80gox5kFJjlweP6gtFk2mvk=,iv:nTeGekHPSGZgGbqEfADj79JAQwG6SbVPsgtx8YX80Bs=,tag:5LNdvT9pg477qkMO390QJw==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLWURZcThnUWt6bTVNbUdt
        ckgxZTdrRTVSTEFuaTd1dTczeWZzTThVM2tnClA5b2NJR3h6bkNnUHFIdE9hcEJk
        U3ZMbWVSRndqcWFwaGozd3NiOExqR3cKLS0tIGtkOUxFQ2dkSDcyTWR5MzUwVGRn
        SW00UktLWHZ5OU82WWlLNUZRS25ScFkKHXcMhoWuUHkcTwiIxT/kOnPzl0UpOD4o
        /GRXDT7+lVfqVdcNt3kcns/gQI0J0ZJumdIt/JVAM0g1UPnT2S2+8w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-09T01:03:41Z"
  mac: ENC[AES256_GCM,data:Wa9mYVq/pcC00VBqfWYr8agSPHdXc+ixrDG4yzGqgKOx9sF6sCeRA5ZvptCUTBVWq3WoyZgFbyfGnaSOl7Dy+8xFux6q45fY3t5PT6u9F8WtMy480TDxeK26sa5PdQ7Jens2Yj1wSTtOTWZVvzZhb09hpe41QMgkjC/I944b/hc=,iv:+4MC/qHIvPKzn/fuo9+uNykDLGcNHsg3kyHHnpVHS9U=,tag:S3Tl24+eOuHboBdB+WS0vg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
