apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:i1WPTkX9O2UArzpdqSKJ/+epT1W+hUanpDKX46A3Hwk=,iv:SNsLU9dcnub6QAysCjwkiYm+bnOMtngJv/4VWkv7buY=,tag:4w/drnXg0wBQWMUbJpNswg==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoSmpWQ0N3bEZhakVMMkQ5
        akZBSnFEVjhYUC9PeGs4ZHZycTE0Um5nYms4Cm5JbS9DY1l1Vng1akVqZDlaWUl3
        d1dGTUM4THN4OGk3SWZya2tnTEdFcHcKLS0tIHRtUnQ4NFNoYlFERjdENElJZzh0
        blRBM0VPYlhyVDZjK1hHVndNVERGZzgK42kcWD58X2ge/xPg+jli2i1RMwy0Isb9
        2zQKRDV5iiiwAZWtJvho43ylZPok3S+g90dovP14VPRxwUepNH2erg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-08T02:29:05Z"
  mac: ENC[AES256_GCM,data:+z5eooViQBzUAzWGYIkujKhI4rZZ0KFOSxX7ecg+qnms4jDqB7MsK4EfP4J92xy17yeMl5Vd7oWI1PLv6PyF1UPp77jOmw25F2dtr6XYMnX9yDhpSOJUDVwucnPZEPpc/py8s7uWX791G4DkH02HednEGAMjKIvXhZqrBzEYo5Y=,iv:6C3jAkrZyyfEgrl/w8O0c6sbcLkJpExggIg2q8OWCyA=,tag:Jqs+0LpSElXVvL1nfuzHow==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
