apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:kbo4NA6KsKSK4L2hLL00z69UzZ5BBWz2dAAoOB4AQLc=,iv:x+XHx/d4rL1BDdv/GpaLtkTbha+3kV6USJyHZloTIdQ=,tag:AwBvOyGbDqkZto1UxRvGgQ==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhSHZkQk9QcEY2bmFyOW9h
        T0c1ZU44WXRwa1pEY1J6cU9SblJVeXYzWXlzCmMyZ1dSZkJFUzUycCtKWVkyUW9K
        d1IrOWtNcEhXVVlKd1hqMVd6M3J1WmMKLS0tIGFya0xVcVhtTkxhdzBUTm1LVFFU
        Z21KSFRHN2JSNmhQdzA4VG8xY1RXNU0KplT5h1oBhvc62oT0cdS8MeuPU5gvpIni
        3tZzKdhuEcr3LRvr8lcO+oEhOab43y9MXI3z8aawIBSEJWI0WCJbCQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-08T18:27:10Z"
  mac: ENC[AES256_GCM,data:giHibnCSSMuGrrUAM+xxtRJXEYMiPDMm6/E0Ly5A0C+OnE5IAytzfz4/Gz6iwkLb7rAysk6vsgv4KurR0gT2CDBz5SSmXnjq4dHsONJ2ADJOpyqK+lPI0xkFpjsMka0CFGQeSpuzKvWyM1Mr+7KE9rh2H06P7l+FWPYfrz98/KA=,iv:doMwQRPbjL+l1Qmzt71sqoYAEdWscdXqhE3rp+TeW/8=,tag:CM6llNTcpcjTOYJtPHBz3w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
