apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:zx3LUtdh6Ql05TeeT2q6/jjxSbXreVChl1oKoO54pgI=,iv:y20mhvgFbgwVs5O1RD8uIC92tZoZi/7xtHqxtjD0KHk=,tag:g0U4DHBgRaWgC1ZAHW/ZQQ==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3YjJUbUNtQko5Sk5CS0J3
        cGFMaWxETzVUS1d1Qm5CRDY3ZkJpWlRPNEFZClgxdXIxTit0SG1uNEtXSWJxZ2py
        eFpIcTRLclBhQys2VnZCK0VGYmxSYkkKLS0tIGF0b0RWMFh6SDlHTmY5SnlrL0pN
        NzR2WUtJR3RoNWRJQ0lmdUxoYUovWDAKTB/kGBiN80kEKJ/Op4FK87Pzo5Nxgf3H
        3o3dDMLJD5/w15uPkQDxu8PwUHjO63A0CMG56J0sus0W5MBMm3MaHA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-08T03:39:47Z"
  mac: ENC[AES256_GCM,data:zDqBK/9iAij4TPd4YuUnOMXY9FXLuxueg6hFdFL/oXzGBdlVdf7rXo9mIiWq6XWm2OTXPojQlzxlByW0+0qRNsI0+ylfrrftnwJTd6OAVFAB/1a3/Ufu0dIxTE1UFIDpovU7uc1mgef6amkzvmXdcb4+HdWgI4bob2k5hHvgAT4=,iv:Kxa/ek3bHPNuKNABEonTTU/SGtvel8KRE64BKkYro1w=,tag:iX4GwYCbERceU33nAYM8Kg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
