apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:uXZgqkCtUiZGh4wKtTTHitFl3tjkjgn5F29adPeWE/w=,iv:QjvGCGLbkLU8mtid1toWQKsqrx/dRm/IAIEDG8gcsGc=,tag:mzrnm5TYJ6GlcKLeRPyRpQ==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmT2lIblpGajh5bENKS0Fx
        Z1VJN3NjWWE1bVBZeUV6Q3NBaEkvbThyQkRBCk5PQ2MrNmtja0JJWFRXbWRHNHBh
        RU1NTHdwOVJTM3BIaVNLK1Y0bVJZRmsKLS0tIDdpTEhvTlJ2R2liUWwwWkZQd0ZS
        YVhmS1ErQjFGc2xoNU83T3pTb2FKdHMKX1cdLVj+vm18uQTdkZWKSe6btMcHtIqA
        8isUiGP/tmNvsY29tg0aDF5KE48XYZzlQZz2eCqif/CTXaC6fl2Lrg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-08T04:16:52Z"
  mac: ENC[AES256_GCM,data:oCU2MJlOUzulI2GFkVccG5wT5R23PzBvpKvdEdMTt6Ad9lSCJamxLmh4mbcuKvVvLZ5eFNk7RVQCcWOR6hU/37Sm83zmJHBuBVr1QwdLt8+xlPNfaEN9qlfLWCSB5/M/vlyWJePDlhICFJd0GIek4byTjBe6idhqpqw3iV3kAtk=,iv:V3OJDypA8Y8xqrLSKZRXjmfs8ZPLtEWIUhkQ2Q8LdFU=,tag:TDLaGJ81Mbh88U/DV7rEiQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
