apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:+dS6Z+hXI6ckqcOhi0awb4kL3V1n4OAScxLCITK1wqA=,iv:C14LzGNVaxo0uvXdaJvSWXVWS1rIBU7TKlsojCwW8rE=,tag:p8Z4u4pKJTv2KVRzp/NsIA==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByUGE2RDJRS0hwU2lSY1Rv
        a2g5SFFwRStJWVdab1d5WDR0LzhkU1MwMmljCkp6aXJPL01Ed05uTTNHRjVLU2N2
        dit0eXh6QjhhMjZVckRkcUxzZzlSNWcKLS0tIGhLSHdEUEozbkVjZG1RVW9ERmVQ
        Q0xNeU51cS9mR25LVmwwaENmTzVnUUkKXjks9YSiAtjldE3RySdB5nmUajtXyvzB
        TrFsV9biwbhbGgKMHY0IG1X1Rv6OZ86+5PLEq4ZogOMxBlRYaTvyHw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-09T01:07:39Z"
  mac: ENC[AES256_GCM,data:Q6ijreF5gdthNTiy163PjUq+l4yVE0EMC1xdpkQVru1bX3fpwGTdOuseP6jh5FCYyDU9Lm0G+oEl2aCTeuObzC8APKA9jLnduJaOVlXhiw0GxllJ1/evU1Du8sE6yidkATiKe8Y0raW4/a+ClID3339zq/hFFtpQJd/klvHPIGA=,iv:KmGIaHeCrr6y0p3RNghhbu4sGNjPYcPq8atIh4scbWo=,tag:lc2p+vkZEeIkJY32ALmNvQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
