apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:QEk3Ykbvahj97czMMOFgRtSWx6SIiXgbnetj9zLjeAw=,iv:8R2pOPlgta8FSveWhKDWbERir6qSgd2g7WOMqX3d3bE=,tag:eruPqJDwLkFvpok5eLyebA==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDUlp5NWJRQlM3cmU1RFJw
        czBUWHZtamZIVjNNdkZvekpFYnZCZG5pV1JnCm00SEdxSzNTSXM3N001TWdOWkQ1
        aG1FWXZKZS96c00wMmF4MW04L1NtL00KLS0tIG1HdjJqUldnYzk1Q3ZBRUZ1Y2Qx
        YXJPSVBLbWJJYzIyTUZZN2Z1UHIrNWcKa0Owu+R+7d2EcFylIssLYp9qc44Pdupx
        XzurkCJ/xtdelhxmFp5umAK5aS9xNB6M9JGIIt9BWrhtBIDAoNr52g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-08T03:14:42Z"
  mac: ENC[AES256_GCM,data:ye1cw5O+xYWqHy+7VlnnKCbMI/OO19I/lsOginqK3ITkegV7LB4AzP+BwTzzerHqHF4QE4J6e1ziXRdqpFEDUctT8SlzNlYluarAGDdhuSdDkHPf6qeWEZlqZ/IzgqIEhWp1SaTBGUQRQQGcX9ldtcyXFi1y0r6IBAL2odpDuQY=,iv:6ZOPttDu+7qyavQ9OZRfbDMJB/VX2dphU2hRhcwPO1w=,tag:4IFqxDS42u6bOecpibwIJw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
