apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:4tV1caUqGmP16r/cmPwaHq72dp4LKHp8q9Eb+9G3094=,iv:19cqL1hfMqRyXRBWOGI7v/N9VFB20eZVayXaRI3SR2w=,tag:v3iuaj1QKFMeoLiok/YgGQ==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVWkVVbHZEcnNIVktYcmVr
        NzNRNzFHOExpR2syZHZaTzFrSTRxb1FUTmhNCnVFS1Nvc2JBZXJRdjdlTk4wR0w3
        VmZGWWtMOUZjTGwvaUNoOTgvL25PK1EKLS0tIEhIQW82dlRBMHY2anpsQmliUHVa
        UVp0Z2RGUWdIb25lSENSZGJORTFOMlkKrYFWZiefxqJGTrKZD5ih91pS9VDZvA7A
        ys1e/UglKfbgwUwdmYu5apSO7TY+vGur4rQEzh+QIIS/N/DYBlh0lw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-08T21:34:53Z"
  mac: ENC[AES256_GCM,data:QpH6IJD5RDOYnz0l05oPvYJsS6ena+1eoCIL//XBdvkTOgrFtGwV9Zq34MzdH+jzIFXPJWknDwJJfxMxY3Pru8/0fLzkuFUYP/05KVkoW2k5IXsjxW9xjTuxK87PIAHccwRydN+g+09VImlpbDV6yKV+8Isu9JwgOYuBsh6kyk4=,iv:uP7tCIMohAsIh4P0AApyUSV8N5chJPFCZNgVklwtI5Q=,tag:sLIfq8/p3H2vB6lyQ7PO8A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
