apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:36Q8Dyekdwj36p90uwu3+CGBUlXkTjAMrQKbxYNCxRQ=,iv:4qFrt+OKDUyrF4MsHz6YxELbEho88SG10QJAWGwvdUI=,tag:VtyA4e6SFg5bz2adSiVMrQ==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWd0ZRcGtCU0tIdEs4QitW
        d21DelJEdnpzeWU3dUlYTWt4ZldEbEFkWWw4CmtDbndncGxUZ3VnK1VtNVNlYVl2
        K255T0QwWk4wbmhSQ2VSTlRVVDVJcDAKLS0tIGI4Vm9tTUNxZEVway9WQTZOYWhx
        ZGxvaXZxK0QzZnRGWjZHZkR4U1puS00K0+tNRVG+vIcSaN5pikeAP6ENUKlsbEGE
        RRYHnCYGEyWgnWq0rJfZcS/Yj2X8XelBh1JkYLm4FQk87u+G7Umlaw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-09T01:29:57Z"
  mac: ENC[AES256_GCM,data:tcp/0AiBJ/1w8zZGKh4AO1rQlc7Qk8bZwOV23qg1VTTzWdTiOKinVW9Y3vLKaTIuVA7CDuDiLlTODiet9mhAkGEyLaR0dFg9RGb1EWfMpahKwqvMuL31RvW23Ud4fp8aeaX87kpehq0U4IQXDMKbyDpTnIkfXdYWa2SJr9C+TB8=,iv:uvTwqix9AmN6KzSvyOBcPLn+gnJv8eD0w2LgCLUXEio=,tag:DDzJ+6dTO+r0PltpM8pc+g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
