apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:6tMp/qgHwJzySM6snDY12M0BKIPVq15Kd6Vi88wk4A0=,iv:fWBR+G91fYM7a6frkQ0VsONDrPQ7d31qIkduThnr7rk=,tag:dmI9jUxTFtzQYHsEsviBjQ==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0empmQ3BWbGl0cVpZbGpC
        ajFwYTl4cmc5aEdWS2JHdndnem5Zc1ZjdWlvCk1HaVBBRmZQTUlTeFNWYml6NHRz
        QmtaMjZVRWMwZFVtaTk0UFNSVkd0MkkKLS0tIFIrczJ2SEFOeEhodjhFODU0czdn
        SmxnMy9jRmZxaGhyZmhBeEM5ajQySjAKKV1zQsfmfOjkAg/iE9AEWVAZPPOVfWwg
        m3CDOzg4gEErYPRCXvdhuKHGjA3fAqVVmn6L0ZOoXwTK+oea0eVNrw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-08T04:08:07Z"
  mac: ENC[AES256_GCM,data:nknkcMbom2KDgyqFeBxzy9CW/LKCUaMbZV2Q4DDmmiYcn8xzW+PSmONks8dqK7qMUGaOQBle0McUqyFEpILgXKsDaB1eFNfexxPheO0Q8QsdyJIOW/ewHTZQa7kKgNNjTvmk2oAJqzNarpVYfYeyECUbfIcP97ZktY+MI9Na8ZU=,iv:EWzWhD3EevvPFBZCKKm+H7mfN3xZkSlAT5Cd5PehUrI=,tag:kN+x9qSGq8mxTJNBEnSTMA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
