apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:cseCg+kNtflNDKCzXVeMQmMud7LPD1CJv+hTgADcrTI=,iv:beXS5/Ru35ejZ+vjpC/4x/UV0GkdWqphT+vZCtiSyEo=,tag:bxlE6IWeyiSwiowWxfvE1Q==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsYmFZYUE0RE94OXlMakJC
        Q0ZWRDJpaEhreUg1MHg3bXU5STFIaHFOY1RNCkZKSTVBdU5SZHJpdll1L1FjNnA3
        TnFFZmN1c0thMDF4WlU2Wm9hYWFCV2cKLS0tIEFiYlhTaCtxQU12SzZmODk2ZVo0
        WGZUQTFRc2N4TldyT1g4K2R2b01rWkUKGzbjXzKI995TZNxSnjVUtbN0lpnnsK+d
        eieYBaeXYarmxCYAzem7weW3pqbnGg40CZvPkm8wGOGfXm/Bz8FYYA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-09T01:52:52Z"
  mac: ENC[AES256_GCM,data:4Y5iUy5Y+330Crem5qwi2LXsnnKSluqRz5sbuS/PZDA6847PTfQ40raaAf++GXotD4sVf10ZkUWewRsAM68uNI9gFVp0lRBd7MA7TZxU2Hna9udo/Hkj7pfwS7N86tTIyqjhO+i007REhmW3RkusTNulI29cqjXtb3a9xHDNnWQ=,iv:Qz/oUDQYQ0KLlAypHVluR9ktXrytB5K0l3mYBz2S+5s=,tag:rv+WyZjaWzeq0zmCjtMBwA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
