apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:3+k4fO+uh3qbiLimPqwjAF5QyBTH6QLeOSZABSKGSno=,iv:EATWFGpgzFQb9lV5XeKjNq4kiE1yTUxgq1xfCE3J8Jc=,tag:PxMcHewsTYrMhECnpdMVHg==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpZDVBSTMzNE9mbFRmYUVJ
        TlhPSkMxLzJWVUZKNFYvVWJsZ2YrWDZwQ3dJCnVWbEs1SCtqV2ZPOUU1R1RiQkNk
        RmVjNjNpTEQxalF1N2FhR1RIYkVoZ2sKLS0tIENIY1pDVm0wRjVNblNFQVBOTWpW
        QVhzNWZmNE1OTlREVWtJa1lZNXdIcDgKycOTqf2TNRClBrl4rCTmnTtnWovpqFVh
        gARzLagonqnh0ETT2rDQWAjZldvaShPr35v0iWgYVo924WHEvoaMxw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-08T03:37:33Z"
  mac: ENC[AES256_GCM,data:nsibegeB9Weax8UDeTHvmBehm1UAQPkMRVgUGhSMva4U3U816b0sl+2AlFwKYVN7n/bySQeWJF5gytfXtBN/uAb6p8n7k+xAkjqsPImqXs0lq+903JjPwrFf6qeQKBwwQAuNCPVGVClyszj+e0rzMajrE15hRTfV4dhhJ2vVnTs=,iv:sPEAECcOXiqUvTwEw3kcelu8lq2EG9h+xqWOlzNN7gA=,tag:h0aDjmMiyvtqluzu+yMWxA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
