apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:r0j9FtcpW0MP6eFCvlVXGNv9kUpkr5qTIMxPnGivqiE=,iv:3r1Q8p+2meuCoeQf+pNgsxD9KcmxFxL6dWXXF5/Lx6A=,tag:2UkTkHPeIRvvmtXQR4XCEQ==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6cSs5dVArVGhub2U1UVNX
        U3FyNHJQODhZYjlhMHZxd1FuMHFoa2pVdVJRCktILzVhVWMxTDM3aXlPMTY0NG1D
        aHFrTlA0OE9BUGZyMUZxUEJ6V2RINjgKLS0tIHkyTTU2bjJ5S1B6VG1JVXcyU042
        aDJpSjgwRWF0UTcybEZ0Zzg1ZWg1RGsK9+11D59tFErLAE9HWgG9UVt/JxSlOZrD
        jq0RmeL01EaXZRFEY694cDW5rmc0/jXXB+olGVhvZA365WpncNkKVg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-09T00:13:26Z"
  mac: ENC[AES256_GCM,data:b+WiXPrvTeksgjRWVpwrIAnv/7VYNC5yu17RjVgvbCXTjbRed+y6JZnF7PsSY6PJqjxxk6EdrhS/IZrgoIkJjRtXtRnQvnsUrxpZpTr9c7XbeDuNyM8qyT3+haK1T2tYCM3TSHY+l+4E7XXoSSmNCiuMZkASQdCvNAAbXx3JglE=,iv:4hy37i4PhuGBw8wmIQmx0U9/RwB1SRc96qlnnTWTRmI=,tag:sAQ5PVq1X8TOUnn2HuAe/Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
