apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:kOO8bSBpE+uQX17xHqzjjWbszO5SRfgfgMkmgdMd0lk=,iv:yJ2Qw8Ei7B9BPdnFhsoVAA1YKHpPrZq2r3P4ABqJBq8=,tag:tgwGraurAYgPbUXcduitdg==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1WmtBT3BIU0hSbFBaNXN0
        ZWR5Y0J1d0IxbUlVZmp1ajg3WVY4OEYzWlhJCm1oOEEvQloxWkNSMGY4bHlMVk5a
        MTNUWjNCMFFobFNCdWhOMU1tdjdjYVEKLS0tIEdVemhTSCtpR3lPQUE2bnMrVDZp
        aEl1bmk0YW53WGtNa0FDTEFJTzhaK0kKBRm+EwR3qj+ogpIiKOlg/DkbPYA+zqUR
        73xexQJHC0a9vcDM4XFJetfiQ0yBtwiODFZ6NHmsQab8O9RKUeV15Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-08T04:11:15Z"
  mac: ENC[AES256_GCM,data:bumCloE601yF1+Spk56c741OV5nHzvXfDF691j6z14jLjdmgu1k6B7kWSvHA4/AYhdkWkajtUitf2LKEL1HkcyM2Kg3fdKDDWP1T8kYIgsSUWmG/m3djwCbpY3cScFXO1r8D/GXJDKWVeAtJ1if/iGFxaX5Ci5m53f2xz7cqBqs=,iv:ppfC3P1M6JiIRqnqJ3sKkZozEg8sECY40K0SkkganGg=,tag:xMjs0NPoD3WW+ANmj744yA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
