apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-password
stringData:
  GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:r/X1jhA/FTmYkzR4wh73Cw==,iv:LZ/rKcIuXIN/Bruc55IbKZKMFFpbKGXgjz8pDt+VCYY=,tag:l3wRtEDJPK6y5l7niiZMvg==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByT1RleHh1L2dBc2ZyOGRV
        OFMzV3dOVjhDVEF2RldmZ2wweGcxU2MzdkJjCi84TlRHdjNPaGZsMFg1M2NZVXl3
        RlM5ZThHeHVSS0lHVE1LZWF2MVJydlUKLS0tIHA5b3FyLzByWVd4YVJTWkx5ZDFS
        YSs0c3IvVERKeStUcGRHcHZLOUxYWDQKp9yzLwJdOM9BIz2uA272+ywX1inWO4Rc
        aocFgNh/R0KUa9R0UQd4ickMCGeCSbCVeM9/iMVq94eJqgEjDnEDRA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-11T04:39:17Z"
  mac: ENC[AES256_GCM,data:IdhSVino75yo71TVRSshB83gA4UX1z84mAMN/iDvs28d5iQwo/poh/qj0hb9ldrKkOiy6u2auc4ye76e9O9qKXgg5dl86eg9Pn/urLL4mLnxVhED2dVVIESGe5MkEZNFoHA4iw3BPjyxe1yfRTt2jI5AGP7NyvWOo4x1zfD2khQ=,iv:H/U0RcSGxRpQggo0fP7oaXVdumMz9xP4AzWU4iLizoc=,tag:/IRZvU4BGC77e4ZNryb6kw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
