apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:rUQEz+sUTlQ3z2B2VMnvdAa2WLwE7kDE2ODpqGC0PmFRfF5fTgDBkf1CQI5+uHSinM4RofGBDMRn+UCB8UMwsKs1nFI13zfHC37ndrFMWK1Il4OWSscxS+/9wKtZzfD/C+KkUmazYasmUfMasMiEYctYAZRDk2ZYJwiSAnktLJHc0GVuQ7LYkY1Qg0jUXr81dWZrY8L3Jv3as6cNZPe27Xfdl5CihaTvYyhu2+ZN5c0CLqEn,iv:i2dPT9I9tQiRyIGrTkbUNORdymJo7EGBce1xH6uI9Tw=,tag:G9+HdxhLi0pwdQVgrvW1bw==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDbllXNUM5OXVDS1pnOGNZ
        UTJOcEhJNVQ1Vm5LL0VqMy9BcUNqaUE3SkR3CkhHUk5qUjY4eU9WTWdmYkwzeW9v
        SDJlRTZWS00zcE91S1BBdUxGTmlPbEkKLS0tIEJISUFZd2JFSUhnclNuU2dmQTRG
        cldjZ2tScmpCc3BIVXVoYVRkM1JUUUEKilNQ6IIBHTIk5snqbWdQmlx/sT5U76GV
        i2s+0UkJ5tvH+JyiKVZZOOlgZL97pv3GD2T1hOC5XXyd0R9TCFVFeQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-09T01:29:57Z"
  mac: ENC[AES256_GCM,data:Jy6r3nYwZXXOgTHC3JRj0EqWmCJUK9MAX0qewen+xAVd002WUNE7HjaL4mFdeg14E/GZvA0i1rWg405oAtQ1D7TtAOrhTU1XY7kBlds+c7KwVgm9ND9lji6FTlUMlRbVPHLBbENgDi7Oz8Qad1TS82aT+nlc1JsFoN97fqQDw+4=,iv:J56oS6kqTJMaPeqUSQ9+tVArfINqrs75XQXlwWF3vq0=,tag:UkvVSVbQAjWjE7DWmD/7Tg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
