apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:9ft6aOwRr+/t79L7uNPk7W6uHGqEsg4aFRD37oArJVaeMw9vRPBS2AEK4ONoT4O7/cL0HxJQckp9WyXIhBknjSJSJLpJtHQdUPnuCO5a7Dlh8X8x+IveSwCjFIa1iE6kcsMxZ+nCnLZUOXVL41yQbdiN4f+om/0WLuoy2mf3OyvJqNsIhQGWMNP5FSZHD62kccJfKaoNldMln+s6pnmd4XJGdnjpFv1IT9s6oqZzDFy4y8Ef,iv:yneFSEvSGTJiv4XwrUoSF5CiVLu+yu4NM5UvuDWr6Ag=,tag:ofOAPf8GbZjgqnSjKoZktg==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLR1pITC9Id1d1RTRhRTN5
        NVVFU2tJeHZKbVpsa1I1VkpRaU5HbzVNcm5zCldkNlpmbDB1QVlIbmtFUzcvUXBY
        REJXQzU4UExvaWtYcmlTMXFlU1p2U1UKLS0tIFo4WnZlZUVFYmZ5QURMOXlUdHJm
        UGFocUFRWUNENEdLRVQ1VTRyY0svcEUKZvf0QT8vvaoDP/52rXo96VrEfzfK0V5F
        28Bjamg1s+19VAWzZ7gotiXRhnODePOq1PdpDS6MJ7+iBzqKahlRIA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-09T01:03:41Z"
  mac: ENC[AES256_GCM,data:h1reAzMNMEsBLz9GSzCiA5jXJiwTv6IKolt4havuQo3jzI3kJBNVjh6Czh8jfwRViNF/m3STEOUdJmTFVKvmtbRttu21u3s7kminy5nEl2kAwoOhJscI1tPGSontGPLQ/w1rln0Km+6o7LwH6DQ6sRp/CI4GVK1EBIywji2vqx4=,iv:9KriYAzuWQhMNx1Yh3d69xOJiun+uvJ9fvm2yCMNDxA=,tag:ZlhbFuuuaXpFSgp3wU3lBQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
