apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:bB1/pIPHwUJelEj4lyXYYJ/5GKEV/v2Gl9IrMqT4JYM/6OdhsVGKcXg+G68SNpuLHwmlbj2SiHKfKKGc/0Y4+BfNh8YWNTWjfS6Q26gvdblYUD6T2Au1BukQL9XMS6LfSLIoaXch+swySR3A3lq1er/4+C4K66xrR29syVjs4Tu5OZWgnKnOa5XxaXHyzA1AWnYGFbrrrWScyC/bFNPhIQECB9Ak3qpc4I2Uo2goPN4ikSPb,iv:kmbjzhN4/RgeVZMdi1shYqlt8/ia32D5cWMhRKmqmnc=,tag:wZTpipmcFgtbeCa9a2+DPQ==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxNzBkQmVTYzRpaHE4NkNI
        KzNCVzl5Qmozd3Q1aXR3aDhkN0dyS3R1d1I4ClBaTTkxZUsyeFdkdGRKa2Z1UFBo
        ZlB4bHQ2SmJBaFdjRWlPdStlNjh2ZjAKLS0tICtzOFVKN3ZWczczazRIZzQxTHJa
        bmlHeEs1cHhqRHFUWHJsUTdPR21jdm8KjhcErZkr1B//aUZUQZtCxnB9jgRueYpV
        BbQ3DhdwGJdFhRyCmuUDpW/CM4OtWU5qTDQu2AZ2sUhXeIzeOsrGqw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-08T04:16:52Z"
  mac: ENC[AES256_GCM,data:Q26FMIt0+88U+hJR/eKWUVcrjNDpq6aICyFIc2ivtJBBwOpw0eD+2g7BGgZ3cZ+cAkuEYwIkatqiC//qDVLBgQNft00CgRApWA8UJuyrfpd86jKEe1Okh8iucUc2R7GezOYYkYwTtQAO4xo/PXYz91Zkm1aBHoO8Cpz0NXWQj0M=,iv:KaAnNePWOnNPQTPxI0wGVCEV4BMWxiQumWncNEQC8M8=,tag:FmO83Yv2DFXrmPv//HcQVA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
