apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:mtAw8ihX8WQogZG6gQHxo0e8Az1RjiPTtBxi3KdBtPmiZs6q93ko1ItmEXPQ4+7kYBmBqmocODPYwxuMBSibEyAMN6mHnXTeclP8RY+A/gT4KYktiuw4+bMnmeAEznI9yhWCq6R6Ngf8PQ12SJt9aTicMdFyLDrzS8YA5t7la+I9WY620Ge0swcMsCG+fkYIspyjydJoX541m2x/c22CHv1MNqBkw3X8lNnbmLVl0c7lDLVv,iv:fyqrUcShGL+/O6PJ+4hEMGcTvwysF8Io9MPojqKcVwY=,tag:s/r+qldYUb7xCEn85FxX3Q==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoT09ENWhMaTdVNG5mYmVT
        Y1BxYkowSHpPYWY0T3hrMjJ6UG03OFVUOXpRCkZiMXRYOGgwaXNoYnFPU1hWalZX
        TURkOTMrRVBjbzBhQlhyNThjeDNoK28KLS0tIG9Wc3p3dFdBWVlRV1lEd2VNQUl6
        M3pLZUFjbUFpMStDRXhyN2cyVzROaFEKR21DizCaVvGa7s9nw7MY24SJv7lJlQHD
        5vbnRw7GsE1xhp0zX8B+g7JZJNhhqvd3FMl5MMa1EBey8JL9lqECXw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-08T02:29:05Z"
  mac: ENC[AES256_GCM,data:oe1slgqYbTh4ywLX+LxSDTfeD9gxZqC1GTz0Cdzevl8ZievoVXY/JxB7asge2woU0CDSW02fXU5MITuxAbC0HvIPJzO6Ll/mPhYLRzvJrVROdICa5BlANqHlgXRSt9S6jsIxm8x/huss5Y4CHq7u35bzDI75Lj9n8K6/eemD5gM=,iv:qAZBRDx2/lDGOxXdz3LP8HhV5yaKWtE4VBqIfM8MbbQ=,tag:EFg6ocvjrEFwPNldfcJ2ZA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
