apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:rIleovAhpUNzxMREOzx47T3a7WXWW9aRhSU2Nnqa4vfk48fYOiTv+rlGWkac8XHbc+boSRRm+yuTyICfZCwXQEQFltG9KTEw7F56E7oCOiwIxvfILqxxe90zv/St4dtDv20K48IUNpr1KzHmu+0GCjJglkeIHiuItY74s9Bu85qj74NBiGj2UTCiA/DTwoHzOMQfMxBL3cqxaEzfJyRqclZNZRwYb87BK5iwiXksyAtTLQCA,iv:3IpEnVddGZKtvZigZoAFLPI7u/ImgiXCK3yXnCoM/cY=,tag:VRJQ/KftSw2JiSp2wxd+sw==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXSlR2aTFrUm1qZXEzMVoz
        S3JwSTQzcnUrY0dWcUFQc3I2dVpocEtBMmtnCmRUUlBpMFNKM0pwb0N5bERPa2ls
        amgvanZWcTJmb2t1dXZJQXNCR0hFL3cKLS0tIHNqdXBlODFDVWV3K0UrV2FNSHlr
        SldWS2REWW1OMmdOcVNBUUcwRlo5MjgK80vq3/i6+xql9xahgE3DIXDnSMjyxfHg
        yjOSk2x3sM4cHvwcGHvaskhjg8gYcNA1AxfWP8ptwYC1QSTJ1Cd1vA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-08T04:08:07Z"
  mac: ENC[AES256_GCM,data:eqgBIAbhi2jlAcfcqqtklVwi0b9D1ItiZ2GgJETD9J0gv199gMt4hjCJZJo3Frjd8Z78wI+AGsFMZuzkK7l9ua9KFze4viza+fhEj/CtGHBq2LAEXAV0xOOKsatnLSRfyoKngBcNho5Az3k2+KhqOaCvICvaKT3ZojGG62oqqLA=,iv:/5yJrNJljm3PtF8jpmb3bd5oJfabGPdaV8LftYXHKjg=,tag:O3iwc/OE2BYhbITDKBgV9g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
