apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:zY2TqFkUf26tNOzL/ZJAQM8T2Uw40S+GNi9qeHjJlsfQc6OnSyUOntqV4g315RuDL3UM6zHe89maNnK3phYOkDQ66opaMLtu+Lk6y75erqKc+EC6aoY4O703/diyiCAi1orZyZytBGJ605My2zAY5A+hbTTsW51tCbz933zLpvSTMofEVkuUv2GgDXTkgjLM2kQKDYu8vjDIQ8O42LkE088B43Dp213RjSL6GucT4cfPtHNk,iv:KSS/J72OJazCBIDXMsmL/N0Y+gAqClZUiNmNlMXMSdI=,tag:REsbY321knuer/MG+as2YQ==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtVVJjV3oyb2YvY2dYVXFM
        ak0yWEdqOTFVU1BNczVpQzlaZW1yS3IwMzBrClgvbytXMFRZdkdJVDZQT0RHR2Jv
        QTl6Y2RkcVE0UmdkbzhPb0hPalFtSzgKLS0tIEcvN3k1VVBIaHVZRFNJdlBXYTNK
        Zlk5bHJadzU4b3pUV21VdnlMU0VjTzQKf1dR6cqcSml7Ge7jJXYbkM04Uhi0NKFK
        9zFFEfAO78eE24hpBSaQJcWwEyXITe9k2K81b2Lhzai9TTzh98HppQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-08T03:39:47Z"
  mac: ENC[AES256_GCM,data:xpW+dExxSHs2h9CeprXRFpyH7Iu2xRxSE0fs+S6BNedFDKTtRs2aShAzNUWadoQfaHTmMJpCGpUgi/IoBbDq3KSnd0YUfUKAl/gltlghjZkeeRbBmReGPttqtrLYbr49c8AXUOkArmMMQ1DsfJgUOKL4z6BtwEQ/YjJU1e+HmmQ=,iv:ehLeqnfXkdu3FZ9pGU4a+Vy42CkjPo/LXqiG3TzfTr4=,tag:5IsRQwtG2siy16RFvav8Qg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
