apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:cTNqalB9uuonFSYRea3A/gZjq5dJQpj54NeJg+gjU0F9sp03PVjGe0+TAuj4xIp8zvGdnLbwy3/+fKXe2v22Tgqfv8oNHuQGO+dXx5RrpUJSpVwOWcngNklqI/UO99//Bj8Aw3BXK9l5eLu4hi6UvkVSi9C9Q4TzLrFHB89WgpXceCAfxjqFxIvBoI3lGwlZjuqVCPw9tx92nBGAIY9ufb097oTVR/RqJjIoPdumnPvOHQ3w,iv:bRb9yiTQes2R7qnlWHY/kwQGRigovsaIrF6Yv/PFZ0s=,tag:VxHnTmBidghXSbKVod0Gtw==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0WGpzK21uOERHZUxUbTAy
        WDNjMURFT2hWUVZwWmRsU1ZSZ0dLK3JrZVFnCnhJcmdDdnJDKzJQMzhzc1V0ZHlW
        RlI3UVZXeERmNkRYUUJiQXo2VC9yekUKLS0tIDQyYVZscW1BM2crZm1pMVlOVlU2
        ZzFWaUZEaWNDZlAzZHlxNXBmK1pzdnMKVjgnoD+xX1vGFtlHwYqgEiaHViiqP0sI
        nVrGboYGDBJamLRH0BpRPJQUntl6DM9I3XpM8TFaCgNRBiqdINtE1Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-08T04:11:15Z"
  mac: ENC[AES256_GCM,data:wyBh0m4n9waKtOMB5MNllkkFbBR2GmFhPzai8zz9O5vEhM6B9KH8bP+PMVIqhuE3uPIovDoBaH618+AtN/4dBz6yR+20vdYrkXgIIONRQy0UhEVZL0PPl35Nkyq9nnk9o4aw6e3Lk4mUD9TUC/0rKotDkPvpWxImVwEXNC+ysgE=,iv:LuBd49KFRxc7gVFzg/39WUbwgXndayYL9CkmUZxoM2s=,tag:5ZKBhsVq7uXt5W3w5F2pjg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
