apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:4IveDg2Ial93wC7glXygNDm+nABH9ZzXuxRZm4EpvdTwh1WZSB9tcmEYVNe0xFWc4fx9LlHfgrRX6FG/So42bisocUOZ95/wD5fa/cQFmQhcJ2j/FUKkWarVJmPbnaktY/5Fu1OcDq1BjwM1DJuQ5zIDa4RvEILQEIKohVx9em7vM1F2Y2Q/WxL4B7P9EuhGaVQs45jDm1C+cT8jOs95dcOVtIQgPqMcocwAzfLkK4XoKMXo,iv:0OCgRbSB4Vs4a1NIGVclHgW9pZJyGa1F0WT2MSJtglc=,tag:ZuNb/9KxVQ/6P1Oh1vn42g==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBocVJKbUVMUGlwUHdGd3M2
        dzl3VXpMNkFhQ2FQRDZoaWZyVHhQckg4eFMwCjlWRmVTQ1lNcTlQQ29YWE9BUDlo
        Nm5aZnFoN2MrTHJXZXlkRUVxYjBYcE0KLS0tIEFncXBkVmRmdnZQYjhGMGFZb2hI
        Ujljc2NyTm5YWHZTbXkraEVqOU5kUFEK6Jg1pA5La/N/dom8SYj0fTAIxl3JYj9r
        pBK69ndZu93iF72Ni6h87dBf73bVWAmGuni/IPqYyyUnoALMnQR5WA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-08T18:27:10Z"
  mac: ENC[AES256_GCM,data:tDYfXHGpKmOMsDs/q/4zD2jI0HmmAVNVMtgabf2m0NJw0nB6BOMudfItWyxPfD7eM40+h/E+czwwXOJIkRjVhf8ZSMWkdRQ4FaKRDY33T6RKAyzkhbtPaWp7nvV+OL2ikQVz4tVfMeSgNoey+w/gFcnIYev8UMy8TGtLQPvXQTo=,iv:9RX75SEV9LgEuwfuOIXTo0ItTzZrTYIjLs1chqLa9B0=,tag:13uVsCftHgszcEvBk7z9iA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
