apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:xL2cwJsgVse0g4SAJ2NDkT3F0QJpDKXdIyyqdO/Mvz/bKvjwYaPGddlItBy9WaI0rAHpQiTz5UyORXR1oAiMWzX6EqLbN2uTWFEX35xBUd5fKZ137nmE0UTySD3NxKbgKl/V8Q4KHuaoGrq7Cgw7gMWi78XsXALsEiDl+lqDksDOPIpFZ1qtgmFIdECKBOTSq3tAPqF3fCz3NgJTtTtfL+CgolvC0H9hZRVsIEHz6kvVa4tn,iv:Cqtyxnr3cPJbXwiJcsysSBCs51Bf5j0FFcSX1rCxzNI=,tag:BzKUjBflX89f4fMglF0rqw==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBobXcrbDFwYnlwYkF6OWx4
        aTN0LzcxWkNZS0pQREg5cmQ2d2Z5UTNRSGd3CnFKSFdydVhoV2VCd1BsanNWWEo2
        aTlPd0dRR1NKcTRiclV3TFY1cUpCNlEKLS0tIE80a2NGZHpHMURyNjIxS0Y0akpq
        dThYejB6ZU5QRnQvbDl6VXoveFlJamMKqBd9YxEjoQWb+8LnScw/Bt3ZlR5u9J8i
        j6niiTR4ccO+LT9JwXeNJbcbFYMijZKAYklM+JHhF4ZjMX/nE1iq9g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-08T03:37:33Z"
  mac: ENC[AES256_GCM,data:OdptrRVrDQzII0K8s6K5tSYHB53fD/bugEmPUVOcN0ANzHMX3w1lZCcOMbX0+yyLX/9qBS6rO/+0v1yigqawqjBanKFbrsPgubRye5zRVmMVHFFLmRQVSycT2Lx2GsvgpVbPIuPKaIqakMhxiHfr7uxvDyWZak+4GcVfYP+gjDU=,iv:fwYODY9loFOvkN5PLSzcgNXQ4Uo+xmrk4GVvtqnMciU=,tag:Ak03ZHU8xn47CKCOYuCAgA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
