apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:OKsY7MftvPWi0SUGfnkka4ke2xsuSCDYw+qmMr4NHOr6k0N0EQotNyeH9s0reKxDgPgu44ma8H+91wc9GVaSGWycYkrz7H2uHenn9f6PLDz/H1M5/r4MszCd/c6uWxlgPbePZfjc58tKxbznQ50Ib8oTifqDiPcJIRV2EJejphf+lfo6fK5OJRbZGKvj4CVs+QJMlr/NXpI5vO36kxs+KJtMPJXzreX7Eb9jeiRsSSfjGjYc,iv:YJEv0V6dQ2mH3EYnI1Ds4Bxrs6mBD4UwV6kjCPZ1u1k=,tag:1tr0if3XvPT7vpNbIs9i3w==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsUytVV3FkRk9mZ1pZNzF3
        KzRXQms1S09qNXVpandvdVZ0djIyN3VrMWxrCkV4SkFBaWFJNEZSWThKSElieVk2
        cmRyeGplVVBvUjFabUZXR09tYzdZK0EKLS0tIEdkS1dlLzhpV2haWWxMZTFHQURM
        Y0E5WWZmMkh5dEhWNFRYSU1Ud0hMN3MKy2IP9mRHcNgh5Lc2QGpcKBP+JgO7c3VI
        /bCFw9VI4tFG+5OoZXZGw70mAVYz734hpQH6VAqt/voQ+VR6VDhRnA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-08T21:34:53Z"
  mac: ENC[AES256_GCM,data:N3+ozHVZUx6RG0x31NTgwO11srCwW5rnXMg7CfRNXB5e8QYF24n3XMc6QnlOIjWxCHWE6RzgnTgdCyRUea7nGJyY9ZygFIjgbXOhX6SfCOxyFH94jKWW+uU3wf4DJHCswzeuUBleGLdfdnsUzOzppYZ0VYQAJUfrvPlO9fv2LGo=,iv:qMgdtcC5G7A9ouj0/Q1V11eWDhZlpJmowC5kESNp4M4=,tag:XfevgfrhsfPHV7JEMasN/w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
