apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:m4l9fI/9dwv2Y4Oxwlb2cnCyPsZykdX91d3uAaGhCplPHTxqP6PRFTt9clw6Sv2UMCBQPSMkDGNberEzM8pVXjmJNNpL5uF9Z0upuXuG2oHSy7xGAY8HFdvde1ICzS3flz3c0oEzEW8H6u2KhZbsarwWsKbBwPZW+gErD6b/FmEMUoTHWxi9n/AggOf5v3eQlw9pcAnD5N0HuEyA8x8BXOnWwxVyb2h9Ee0pnVrYtbaGJA/3,iv:+OuFhZwLHUYP5rsSP8AWN4+VHjOvZk5WxTe+MBh9jXw=,tag:QZmmDzffS93CoowvUnm5EA==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2aDFUd0daTEw2VlJ2bm55
        ZGplMVRmZFc0MXJFejdlcWEzNFV6REthWkhRCnlpM0VKeG9LcmVLeVlqUGxTNVNj
        aDViQ0Z1VWpvVXRQWXpweGZvYXBuekEKLS0tIEIwU0xPcUFLeDhtVkJhbUxyUkxu
        bWt4L21QOGtTMDVPV0dTdWVHSGFJZ3cK1iqBJE2By+e/tjckELNBpiUh3hftHW/I
        PIiWh+jzpnQPV6PVRAIk6GRddHH6ieBID9v10I6cYuci7Y/KlYZfIQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-08T03:14:42Z"
  mac: ENC[AES256_GCM,data:8p9sicFjgTncIkiQ6aWmnP1wg6e2kkiqsk4c1wntzPd4C5WixRwuTvFLSDWzxEMBkPjgJfsWjhQ0p6gAQOWLH2SiJn8XJPkqnW5ayLgHQuIJ1ufoNzFqmyKrrx4uZ078ehNz+cPEcwaHuTl5ekZ7jTutVbjvqY2gtRtJ0TeyVIo=,iv:6Hz7LOiLDX+Ewlgw3Y6qjjjKjPhkEciSeKtGtX+2IVE=,tag:JoHnsZlvO7mIN/mnNQ6e/w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
