apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:egvRiSRQDwpPRR8C9FJFbphVGqfNhzB2VRusCX5nXLx0cR9fuUXvTas4Q36UKImkbV+viFVZVExugi3WV/Z/QqeR9Znv75ExaQCSFkIqmKNuKiwO6C274EzlyJaUMbQGdnTV/8OMrX1jG+ilnsTTBTSC7WnFpyZxkE+6K77y3ZK9n2gVNjirc6A14hn0uB1fv0r2ONleHIiNNVcvF/bqxgGksCMVKkRQ/uWO3fNwukJipBfR,iv:oini3DT9A4U6luzQi8leRo2vjMhjkzjAUTJerIaLJc8=,tag:SlY2wUSBvA2GbWlZoS6eYw==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxSnlydzhEc2lRT1hHL3pS
        WHRnWGFET00wcmFSZHpBa3VaSnVJeng2RGxJClRoVjBMaWdsNGdSYkw1M3AyaEpU
        QlVGRndIcDBqcThBdTFEMFZDLys0dXcKLS0tIFUrdTVlMFZrdCtOQzBxSCtGYVk5
        Rm01QVE3dVdZVFBjQTRoUzhSOWoxcncKAoHEtoQwTyPclVMQsHz8xikHWqN5uToH
        0BoPPeohzdmmPlmHClRUy8yCzauFd4gpi3/Z66vQo0A704Q39rSVbg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-09T00:13:26Z"
  mac: ENC[AES256_GCM,data:f4f8wGvoZC3j4Iz45RyyDODcH8nGluplJWxpgpdNNOHnhYGHHt1EujamJT3mRiuUayFoeauX2oOHw2TN2szrR/IrVvZvC29FN2HXe/bMTvVcgTMdGUW4pifG+aKO2wAfK2G086eZ+wgpjM27ZP/jr6mmntHv5EMiBAKF9GUuUY4=,iv:FKJcp+MLtLSNGvyDZcEQ6tFwrAFrqXn8h3mEnjDBPxU=,tag:hwytUhZOKZqtAEAWiddjAQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
