apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:1YuCyMJui92pwN3qAk85j+voMZGxtm16WQcBb7Nzx6m7+jR64geHTZQFsyd4WCf5CDn9l/mlzzsstjy/75Dydz7Kl7wymS/lgOVxgCUwyc+i7TZkSFQYTG5UulVAX/VEFT8g6QwxTGZKIWSB0pNAP/Lp6JHfkEw0VvmotSDKN/qCRd5zISq9xIHbYxFfwdX4yyuw0Q75robjLPY8f5/xIFW0btHOcy9mzxG+EZG2xBRBlPRh,iv:B/MsdWcBffYg+RzOqjbRGMVoWgoSbGvdAYlr5ezengU=,tag:2x4QB5zf/2v1nmwHzMelVQ==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwd2tJVXpTa3lTanhuQWNr
        RmdGaHMxZnBDL0FrbGpqYSs2RTl0a3hyOVRRCmxjdEFaMnpJZmZyaUhlQnZwV2ZF
        SUpjNWJEYURzTUpJMWRRMEdtQXh5MDgKLS0tIDE0cXR3UDNOdW1JbWVFVStSNHk0
        WDVCV0plZ0JObjBsclV6ZjVIMFN1S0kKO/D4iO+B5XtQC1J7XEqhlmq9W+zz9kaW
        M7cGi0RwDxUxQXjCeUOTGzrnOfgYJxXd+RYaT+CpZ5QAehLNhXV6XA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-09T01:07:39Z"
  mac: ENC[AES256_GCM,data:3lwUtI7YOiuVd4VZLOc5DK69MGzdSF3d75SruBJHp9txdsMZXf3mziJ6Dt+wP7IvJuGjTrDn26x+AoKjaEVsPF51LDYOBYGMznZdohnPgpAaUw/870cDVxU+hHayrh+7NFcea61DfFZCDXcMmACPLIS2FkJmDH9vzxM2obj5jo4=,iv:J+Njzjtv4XitHxTk88ganpynuF1U3/YzQrLoNjhP3ys=,tag:BuCluZTLcgy0HxNzpw3yVQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
