apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:XWE89XJIaRXTYQSia6VIXcZn8c+FwG0A2txsmd4w7FzVDFJICVaaIr03yqtURW7XUWS5JlmQfGjJht9Aovdu09Mt+Xrmp5qnvbv3JJ/Clgujk6SJTcNZ5i+lkY4oiQVnLPJztAzm/4fjTE8o2jSKNgGZuhBGwDAd/Vwlj/DOkcMYWzR68gBRKN7V3PUwNoKfPhK1Hzyti57Rf7SZy+j9kqHxdGW14g917zB8sONX9ZL+N7Q/,iv:enbRozQYAUBBrlLe/Zxh4q6mE5Ewd/BfQocZcowJy3o=,tag:57jiabsaW0I1V0aSj+y9xg==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArL2krMWVvNGxRcUQxeGJm
        WXQ2QWdhcVFpaGIza1ZEcUtBekpleDFFVUFNCnVFRC9Db1ZFRkJsNVJEQW8xaTBF
        RTBkYm9PZ3kvZWdpc0ovdERVVVdmcW8KLS0tIHNsNjRPN05DK0ljbGZsZW5nY1BI
        MFJhTnhOSy9JVHY5SCsyOHZhYXV4NzAKaXBYuIcW4UiSxh+4rlXAE7Zewv90tVlr
        wXvztVLcW8SEpeFOfd5CjHpDkZ0+71/4xr6z+fDMyt9+ZGAGsmDKNA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-09T01:52:52Z"
  mac: ENC[AES256_GCM,data:60tQjtYizZv2DSJHlnqo8SbFwDBroGldoOIWho6zw1Z6KgzJIOv4veNSwbIMBlhfhglBBTy1tcSGV7uuHcW6JjjMRRWEY3YbmSsHCEjShQwoK4F+92kSeplIilw0u3UwL5jz1HxAJCvsprCG/3fQRdHACv2iWYhi3ayi4SIiukk=,iv:lKinmojS4qX/QNjhJFAEt8m2iGcX0pww3W3sWJCBy6E=,tag:ZNh0C7TT72v4qWsHq/w9tQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
