apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:lcxxxY4atNvvypi+HRuWPeUWH2Du3g/xDhHb8wGtRVXQYHVgq6VQag==,iv:u3/qMQEuLb6RB1Q6VTsfJEpYjdmQEHD5OGk/AJEhY0c=,tag:/1wS/oklqU/ea6Zqoue4Qg==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYYk8yMDdMelVrZDlIenpJ
        WHJ1SVpGb2F0Q2tkaktwT21LOExYYWlSSW1BCjJUZDJFamdFZ3owQ0hWRmhwMHBT
        emZmdUtESjFxUzNmbWFDY1NaOUZEM1EKLS0tIEcxRnpUUGcyeHY4djNZMWFPVFlK
        OXo2OVIyd3NwMUpiUXEwbVFTczVTZkEKt3lMM6abQqvsrWHWuBHN74c62lYIS343
        2MG8xYocozO9ZKTUYKn3ZqQ70iuKObc0hd8O4eQv8Ejzzrs7lp4AaA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-08T02:29:05Z"
  mac: ENC[AES256_GCM,data:eyWI6nkU4QvvJsrx7P5UQjubZ/R+T6nNH6TDs0lwrLsHEA3G0xz2lA0jwEtLiQmahczDjoBlwcuCwXFEpPluDu34SQoWUEMux39JLZtTwzOB6TcwUx+bE9FXlBUiK9frhqMcrxespoQ0lrl9bzHDyHnGpfQUmAia8sxoPDshoJc=,iv:Ypj4jS7kxi1wG+kSpIXOlvl1SXzLedeJ1NgyqXsoHWo=,tag:H+ac5pWskIxj80BVN1+4Fg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
