apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:W4NI1DloFhGhxpx1R5FEY1X/4Y+D9b51QXmB6siKjJC6IUMfBbdvNw==,iv:Iwcbv+FmafGpu1T3YV4F0/bPuFcqEuNIoZbA9L6YU3w=,tag:GyrTtZr//vbBCycSontOBw==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIdGdTMU5VN0RtZ3VYZ1pC
        WTdFdFJqZC96TzJCb1hWZlVxTzd4UVNDZW00CjBsaWpQUmlwZjdhQW1aMkswK3BU
        aklueGdLZGlCQTNONCtmVzBFbWZBdHcKLS0tIDU5TWl5VlRpMlVacGtxTU5MZ0ZN
        eTVYTXNOc3BXTXNUdUlETVRCeSt2RncKvRQjQao2DAsPHknO0SQnvDjYZLKWus8F
        6iE5BwyJjrcQLphEJpnmnZmh8S5iW4n2iKJjCXeH7eJZoJoUs8LWGg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-08T04:11:15Z"
  mac: ENC[AES256_GCM,data:ZCqWFSHe2dYP0pzRTU/5H0pn+uwkk8FYUbCRE6MC/56L59QNasXH5Uvl5EHlYhNmeqUdk6bU6wuIQK5TWJQlqQWzKscSZjEE3mPgxT73jNOFGG24rDbFVOMBZHjx57oF1k3M2oohhaMp5X4Hrzhs4ZWayyEH8OxWQbLlSDpORWI=,iv:sOUH13pCDjzUkj0ZwP5+MeK6u8QQYH7C3t7fAMqUmrM=,tag:pvm1YqnbKpoE/ggvxdoU4Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
