apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:di5eku+AsU/fHtSBh0Eausz9vYu7hb3gVj6ZeoQ71fPvEmGyaL3n0w==,iv:PidfrBk7F8qjYhniFT0jWE/oHEMMM5tF/JDdHnrv8UM=,tag:OS4TUNSGFL6caarDsebPvQ==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3VmYvL1hQSytBTkdrOGIx
        T1p0ZFJhbU1WcytmMjFMZUpOSENyd29EcTJjClh6QXVXb0RDeUxCZG9XNGtENWsv
        aEtHWHA3QkZpeGd3WkRTd3d3RXJJWGsKLS0tIGpObDI0SWtub0Zld3dNUTRUTmVk
        L1ZsczI0U0JHQk5jUnROb3hhaWtCRUUKNeUFg4ivl8Vn3uiWMk/7xNT0gA2aarKp
        fzeK6giIgdAIsICNZKYH+J1QKrE5YWZ+DS5mmq8+ybbgUu7Kz5j+hg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-08T04:16:52Z"
  mac: ENC[AES256_GCM,data:qcp13KKVcSVdQSy+AEOEiZfS76LTayNGPg3kj7V3mKa+hau6CbKJfcjJgq8PDMkj84BhbVsBB1kkWCwwI/GMCb3JaHpmcAaMa9Y3L8/OuYQx0yVOHHqQ+XRhpLmMO+VRRLdnw4kmbmNPfUzZZ9gGml43KUy//iKgS22NNEtfG0Y=,iv:WAG9/OTv2Z7mEQEkS+aUYN0EOu7avYSCR7rF0R9KZDA=,tag:ZaxnzpXgdwsv9RJsHV4Jsw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
