apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:7lhHE2/KeZig5fDmeXZP7xzwM2b1jIf+IJG4RSo8rw0n60xvJN5JJQ==,iv:0PIkUoop0rN1w4nfOLimS3gJpIc56MGpWSeD76TEXvQ=,tag:qO9gx51DLFhk8HWVy+3BRA==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxUDBIdGE5ZWxnV0xoV0J6
        ZmYzNTh1RW94blBFQ2h5N1lHWjl3ZjJYWUcwCmsrSkE5VTRMRHVpYzhDN01qb2ZG
        UzZDajJMZWVQNkhxSXpJTk9TRFlnQkEKLS0tIGxGR2U3TzEzTzdLMTk0VFdtVDRw
        RnVyVVVjOU5LWjUyYVBPaFNNT0diMzQKE/xymrTS7TcWZRp+54uSe5JfNxTynuen
        4Nr2/K6Qw7INZ9VqltRonI4MjOH29mnHDrWLmwtUTD/ls51QzEIQRw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-08T18:27:10Z"
  mac: ENC[AES256_GCM,data:jcubZn16De0FMPV0j92cFGuUYIShW02SOCCgGU5jHoPAhNhtP5T9gVk6vgae1aYYua6YuQfCTnrj6JH9ZTHJ6tdg0g7wtxb0QDqak1xDtcIcyh6HYB7qn0Vx02ihQIVgPFzWz5pd5U4Yy+OoSYO8QJ1rAw7izhASsx5Fu1ePBRc=,iv:9N/6oJHPVme0lbF6eRKEcy5otS3Mk5bDUq1mDDvApFI=,tag:A+RWfZVw5XBhk188q+f7pA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
