apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:A454Jid/6/uIktdsAJwz8V9xL7yA5oJrK8YbrXIEV3lr8F3CmITOZw==,iv:NrsmdhzCuPKm576EiTVZZNliBlWTX0cSS9TYxb9iND8=,tag:86uGpNKqRFQe6gwmX5USug==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3bkFJZUZWOWp0aUVxQnU0
        V3dXNXBzK0RpbUJkdjJBNE43elJIMkNDYXhFCmZhVGk4c1dxSDhxVVRYcFlnM1VW
        cVJsY25mWmtsVXdrbDBlZUgyQnV2cnMKLS0tIE1WdlBZYkZJWVJGK1RFK1NmZzlx
        RE5SMndNUzJER2NEUXNURTVuWmFLZWsK4+RY3+BSwKTUQz2pEr7c1oy7Hf0wCsyG
        r2yWvrZFPXbqO2pOzQ3K83jJGUJ6/EdN7JupCQm904+u2aQwyfukAQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-09T01:07:39Z"
  mac: ENC[AES256_GCM,data:f7BKfjVyntwhytFPyuKbtunH0R7Lt+IzkZfNnQGx+ooRPkKQbMoMlYcvvxwXhYcdSfhY+w6qwgldFQ1vY0/CulmeLo2T4gXA9psota3hVzoyAExHyXEwlHRyXr10h3S4SRZgNER+VZFGvGA+p9OjT7zVhztdm+o/Gj+XjqjZ3gg=,iv:Dher94F8UzWVMFUNu3MYIbwpA4GWaIlUfX3Z52wnvLY=,tag:ORkMXoj5T7ggajtMLSrgJw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
