apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:QMjQhnhZaBKh0y73y5IxoTmNNeAgpczGHRLDsUFRlg+kGPBtcBRDtg==,iv:C3l7S5cge7kKU8X+tgA3sCs0/y4NGR+i6ar15L/BPaA=,tag:1D2gX7uAHhfz7LOUtYPTHQ==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXRnE5UkVFckRKajZWK1R5
        eVFCTmc2aUJleXhqS0hvSG1EUUVnc1NxVVVvCkYvQlpQSWFuSTRGR2haWlZTNHpO
        enhKbFNNQjVia3p3V3c3cTQ5VlVNM2sKLS0tIDJ6TEorOXVlc25GTXpLMkRyNE1N
        M0luMktleXNzK3JEOGZmVGdXQlVtdDQK+wFHrhc3EKNKmoXEElSbYtHhNxT7pCKA
        rNLDgcPRBPl4Tfqhn7XN7NegioWcdosvisczx1sX3L67WzTNGS1uRA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-08T03:39:47Z"
  mac: ENC[AES256_GCM,data:neqCJB8DFW5c4kW+p+kXjxhpYM85u30QoK+8TRmRpYoAIhsQ3KhhhRLhVSjF5nYfrF3WyVXPVvR+jkCn+/thHKtH37oAW9/UhNjrlqX2Ax/c9QnR214kpb1rbrzunywvoQB76U42tG5fYQS8/S++H91MGCqq+v0mT5LSJ1rHkAQ=,iv:PC6211FsBsbPv/AyexM7DmM1cR2xPjXlT11q9wUakjI=,tag:wvPl3Q2hFEfuTHBYBkwaIw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
