apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:uUzV9hIIT2c4QgTN53D1zhJnyhB0J9nVv5haUa5yjkjDTbsGxM54xQ==,iv:yph6hrF2XYQ3WXtbc8vYhyotz/6ws+zOWX+b/W01KZM=,tag:YVW0fpG6rRgNWKPXTD6L7Q==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQU3RWK0JrWlJXV1FCNUtZ
        bEU5ajYyN0xXaytpaVdsc0JFYkRndStpb2djCnpJOVdmZStqU0orS1l5enBrYzdy
        UFc2ZldyNGozQTJERWFsbWVMT0VVRTQKLS0tIDZXSHhINWNRZmRYemdFZS95WWkv
        TkFFZE45bFRvTEk5OVhBZEl5V0xHa00KFuJarDTjRwF5y5WDHEZF2hxbsfg2BTtR
        mBn40LN8LBq5J61dQBWHpn4DaALSUD7jGhZ+6ohcC/GCaZgF4rd4wA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-09T01:29:57Z"
  mac: ENC[AES256_GCM,data:S7u5Jn/TB8CzefJomMXjGZjNaebsa/8ivC5+f6Wn7LOZxfoavUhpJefT9dZ9zSkICfv1Ibi0i0U9rV57wGJVEypD+9eThbXwaRHauTwP2dqm09uSpXwQkVdYddiiGn1wrH+SO1+j3GkytP3n+r041BTHmizIX65DBwRjEoJbTWs=,iv:f/JX8pPoSWLIr1sM370YN+8XnTGR17edO2SqQkTyBl4=,tag:G8YcdYlhOcuoJS+TtDSR2A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
