apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:+tVBek6vuI3sd82Sd9KoGQM5TPgp/k975/hn7FGj9aoQBdZIi14J0A==,iv:0WG2xLEzwh3hoKdn30YuCs5H/J09c5Z1Yh840WUu11I=,tag:1z2BywGMxfDryl4vA40+SQ==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnaHpLSFF3bk5oWVFBdFZY
        anhyUDNGUnFZdU5zZTk4dTBsZUU0VVE5U3dJCkVWQm1JeEIxeTFCYTg2cXZ2QzB4
        VEFYc0JQUk5zV0hUQ3Uxdzl6Zjc5eDgKLS0tIFNxY3ZjRGVlTU82TUdVSU1udWdq
        OWViOGptcXpQVDJSRFlaLzhXWlMwSGcK5KlFkmzBVqfjN+oBIF7LoFy4D3QmZHr8
        3WWSH9XD785eHmtmXQnVk50mlPeP1g/aLX1BM60zHP7oX6HdnKBVYA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-08T01:47:42Z"
  mac: ENC[AES256_GCM,data:UPll93lUi0IWb3U5ReRLS4qXl/S0WTZykeh5dLmXYjSDBSbwlS4Uxqxlll7Rj5OIUVavbntRDWz+WsF4yynBE5XWO6HzpYNYud51ONx4wQ5tyZSf3Kpyo1wmiDzA7mWUhoNOpjCfLFBPOwFupBr9QbHGCFdKgrIa5MrIUKltnoY=,iv:gwLRZn2b5Oum+MWgjpzXIQcoKZPaAsv/4GZBy0Gm7f4=,tag:FddkqwDRj3auwyODi+iJJQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
