apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:zCH3h9gU54m+B0jm+7fq/0pLhJ5CrB7fW/bbE8RIlTYsgjolEF7k2A==,iv:0qhgc6wK9R4Wpk34DHwXLaqnwZ+6zBtafi0afwLYkBI=,tag:aS3KEScxRsi8acKVCsetWw==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhNDhCdDNYdUNrNGVOZjVa
        RUNCdWd5L1FYMVRXb09INUJUUUN3UmRySkhRCmQ2T3dxR1IvRmtnZHRLOEZDK3I0
        MGcrd1Y0TkU3Z2FZMTNyU080bEREUjQKLS0tIDN1SklOMG1wZXZDMTNCbjFycTdW
        Yzk3YW9BSzBhNkg5eXlTWWhQM2dKT00K2mqjQ0UarlAouL1mC4ACLctwAS8DcK5P
        ioCPxpwQxTcLhEiMf5LJGJqUL9ltRE80+/BqSaXobX/PpUcYhg74Hg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-08T03:14:42Z"
  mac: ENC[AES256_GCM,data:uhQjuW/a87SpcIu5FYTMN8eSv09J2BkgzjDIbVam+Wp+Z7+yMXPFhz6uZqQnZKurMaXjekEsMs0cljaZRYCbI7rlHPo+oYjOoSj1LNN/nVMR0CWnBn9oCih/viOIGOV1KmmIZ4xd9XpwOvfIYMtfhpL8OO5xVBLk6kGJfFMQZCQ=,iv:wECjhuKqX03oQKXlLEEjGOL/WTudtCbxnqaKBlalmEc=,tag:GLuYsR4L3LIDxsE9uzDPwQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
