apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:ot28D4GECgmGz2MFYbzyCW1h+xPv0XiXiz/9C23je6VhkeztehYbpQ==,iv:6Ns+0Ib1DVdb2k+J8tHH4HgdyDHnh95PAF+41jTGmoY=,tag:bjxc6+5UsHfQEAlv0aYcSQ==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpMnpDWE9YSWxvLzhiZkp4
        azZ2SlRBSitZVmIzSFBPTGRqaE9PbWh5ajE0CmkxZkFPVG44Ti9kT0tjTHpRbFla
        cVVPaTRxWDJrdy9wWUxGQ0ZQem1XalkKLS0tIERYV1Y4Q3NDTzJEeEpCRzRUQlFo
        UDFyYkgrQkpCRVdLYVhHUmJ6emtoQzAKi94+A2OdIJF/BKeinhzqiwS02amIgExh
        vZdOtxj5Lqj14etxUxMs5jsHPyn/J2iIWgCIbDNPmwpbv8Mj+Y6G0A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-09T01:52:52Z"
  mac: ENC[AES256_GCM,data:RtRozECiciOUo+H28fLmF4zWPidbdxj8Ogq9ksWSDCcCPDNMjb3I/6SNiWKWrDBnePVmf4U/4MJuN5in1xOBr841uIJuKEJGY45ZeQ7GDriUyQSpO1ITctZl1Jbrv+K61Unpnv8iCIMMGUVfJ1npIhMrLxbHBqpuxICz/XIESHQ=,iv:YHboS5zRMPIo663Knbb92AbBU3qCPLltpBAQeDSn3kE=,tag:JAm/mSb+byYG36zJwMU/zA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
