apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:s0Jb8Kdjt/VwyG0OYbeeJ0NBiqoMZBr6TNRf8KRmeC63tDC2KHsEmg==,iv:gVOwpC+yf7UlOnTvCiWS/nLGWtE7IuxMfXcHTHh4XD4=,tag:5YUKZnopzzC9clzRK7BflQ==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhZkJNeVRMZEhVdkNyQVFm
        VTdiV2VDRkhlc0ROQUxCZ0doYno1K1ZaT1Q4ClhhVUczb1hBMGM3OUxmN3doa1g4
        MFN4V0dpQTJzaFBCd0tEeDdQMndvT2MKLS0tIEtVRzAzUXlVNHlDd2FQRHpWUGNv
        bXBoeXhWWTZXNTFsQ01WQUFZS3QrWmcKSc72KM5kNkREk7gnDrzZNNa+eDy57ZhB
        ZZWcbcmwA9th55kkZ6fFTQwpjUEy2PMKoC7RNIg7XqRaKP6fj2hDWg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-09T00:13:26Z"
  mac: ENC[AES256_GCM,data:8l2s5tsjMdHoca6k/fVK4rWKB+YwClZtl1j5zsBf3r6FB6EDAYdc5onDXuw1b/Msr33dKeSPG1cDSTJ9jnbULF8K+AZxzyPmjSOV6Zzlsx9KDxWk7wrO2vFf+vugPaD4io0aunJG/hkssCsIThmHjY2OamHix14353lIxEHGQuU=,iv:PKt2el3tCvjvpyDpDsIU8Vp9MyLfa3RIII3pxPh4t6g=,tag:4F0X1iKEfevV6MIqYNC5fA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
