apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:0NMl9olhK2TEWb2q5adV8ZlVBOISHa1xO0PY4QhtNdWfEvzKUYsmUQ==,iv:MqG+aiVUrFgedNLIoggX287Aqci06gnDUiXvupqtd3o=,tag:pgqV3goEEx7B5Q9OrN1d7A==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpeDhCRjArKzhLdmJCcWRB
        cDlyU0JGWXBSRks1NUd2Z2JaWXg1VEpyaW1BCllMTktSd293dTJRRXN2UE5ZWFRO
        RTAwWjFaOHIrWGFlYXJBazZnTDh1VjAKLS0tIFdXZlNYakRraTlyZ0JJT2JINTI4
        ZjRENmpSWVVmSTIxNzRVZG05UmRtcGsKYMeFSE/4ROGSaKZsLw4AwFosQcm8DP5f
        oPUBbh23liLeO/isLFlHJDak6G64Az2ZqfLHiQZDkLEssaQWxRx88w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-08T03:37:33Z"
  mac: ENC[AES256_GCM,data:04bUH0j5PrBs60qp63dMUNcfaZea7q32wNqdU6Jf03shacl5gsDfWEJRCj1EQxPIqhctbEs5jXICAGavG6wHhcbN8Kk+9MokBTMR7BS+Hyr79V9cKe9lbtkyo7r9PUMHqWaJAxOOzkllkgen4fOE+woAg6vOUGFzY6WJt7pxJ5c=,iv:m182/jXfwm62uklpRegwE7dfhvyMYwIvNN37PxamjoE=,tag:BeQ9RAsXFtQnaa3WxzGYKA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
