apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:X0KgJls3pyfyOlnJYGmPi4uV79eucE/7hsIduhED2l8dpcL8kS1ztQ==,iv:QZOzSBfaw0qGWNuBWysK0K43Ii4ZouEn+OAL86q1144=,tag:htgRrFBXgsSCpk/BDX0ZQA==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXeVgxL3FGQUFmTHNycnJG
        SWhpREpsSEZIM1dmSllwNXd6S2c3VEFkdlZBClFxcFBGdFFhQ2RWZjRyNmR5ZlRH
        QlF1SEVoY3IzQ2MwWlowcG9ZeEc2VkEKLS0tIHBaeDBZS1RwMU1FeXhMVGpDWDlZ
        Q2pYdUhkcWg3dDcrVU9lU1lrVGhTZHcKPFUumnIeWwyWq2oRLnThWYlf+PaRgPCy
        KP9/VvTxSUZUXMpAY3iiXfnQnY0/FLCk9CS7ktGslDq/REfIG8B45w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-09T01:03:41Z"
  mac: ENC[AES256_GCM,data:ER1ebpdnYpP2NN+d2XFrhPYUhHmbMRBrrW9YM3KnKP6UbNUQz7qUyksukV7SkLetQaHywcW9POfo67NFN9Dm9ON3Ki2C7Fwn8yTHjpwkmd8zZCS9xE61gg3JEoyCJdCBpXsmfldcCsIZVKU9Md1x4rldNpUTU3PtX2apeFIyAnM=,iv:JWL04IygEngBkcDwwdk/U4PQ7Uvo8cj7MHKUQzW2c04=,tag:gp0+abeZrOclhEUhF6ExPA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
