apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:lmbmlpkvWM5xPfafQ1FqpL69WzOiBZfU9JXsWgkD9cxnjo+T9ND4rQ==,iv:zcqmZuyfeCiGm4oqLsKKF4FVJl5RFV2k+sgi6L5KRz8=,tag:aM3lv3kkyftPRdbYEfYNrQ==,type:str]
sops:
  age:
    - recipient: age1h59k6g8ntn3htf06k73snu6v4xertqrmg8tel9tzv3qlvu578ueskg9neh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3elJLWWtHZFdGdUt2VDU2
        NUVMajhlbUE0REl0dnlQVkN6SnVsRk1ubEdBClozQmtWNVZheFVoY1U1NkEwQW9x
        SXF1ajBFTjBLWi9jTmxZK1ZLVmNSajQKLS0tIGZxKytVSmxvaDhJWHA2SVFuUUxj
        c0dkL3UwbnZIekhFZ0ljbkl2eDZOaUEKntgR05IIgnCip7J70uCXp2OfUh9l+0x8
        30D5PGbDmRQOJyOrF0fDywpOBUskW0vd9tYO23702UHST1n9PnP0TA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-08T04:08:07Z"
  mac: ENC[AES256_GCM,data:6JEqyal78U3vLukANiNLAB15XIbKedQqw1zgyLEIaOZyZLswDT5b60+uv5wWdnAZb+dPSEP0pBwSuLFHZe0oBJ29DAnbYNOjGGaj1wb0h8ev+A68HjrpCvSAA+qOSPSzXEA3jlvRUcMoYaJOAAiS2BYMDUfIFSsQ6FTHgRsTOUY=,iv:nmo1RZMl3PeAzY2Zi0XdDgY96iKySkZP6E5OoeVr21M=,tag:hxB8iBCrNiZCZCcK9tu+Qg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
